In [ ]:
# import the necessary packages
import pandas as pd
import mysql.connector
print("packages imported")

In [ ]:
# Set the values to display all the counts in one output cell
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.options.display.float_format = "{:,.2f}".format

In [29]:
# make a connection to mysql database for extracting the raw data
mydb = mysql.connector.connect(host='localhost', database='salesdb', user='root', password='Csoares#12')
df = pd.read_sql('SELECT * FROM sales_data_etl', con=mydb)

In [30]:
df

        SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial EmpLastName  ProductID                    ProductName  Quantity      Price
0             4        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437                   ML Road Tire       437    24.9900
1             9           1         Aaron                 4    Alexander           1      Abraham                f      Bennet          1                Adjustable Race        10    1.6000$
2            20        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437                   ML Road Tire       437    24.9900
3            25           1         Aaron                 4    Alexander           1      Abraham                f      Bennet          1                Adjustable Race        26    1.6000$
4            33       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26                  Flat Washer 4       530     0.0000
...         ...         ...           ...               ...          ...         ...          ...              ...         ...        ...                            ...       ...        ...
129464   129366       16281       Richard                 M        Brown          22      Johnson                h       White        369                Classic Vest, S       873    63.5000
129465   129399        7477         Glenn              None           Lu          22      Johnson                h       White        390  HL Touring Frame - Yellow, 60       390  1003.9100
129466   129427       10738         Julie                 M          Luo          22      Johnson                h       White        323            LL Road Front Wheel       827    85.5650
129467   129430       16281       Richard                 M        Brown          22      Johnson                h       White        369                Classic Vest, S       873    63.5000
129468   129463        7477         Glenn              None           Lu          22      Johnson                h       White        390  HL Touring Frame - Yellow, 60       390  1003.9100

[129469 rows x 13 columns]

In [34]:
# perform group by operation to get the counts 
# tmpcstdf = df.groupby(['CustomerID','CustFirstName','CustMiddleInitial','CustLastName'])['SalesID'].nunique()
tmpcstname = df.groupby(['CustomerID'])['CustFirstName'].value_counts(dropna = False)
tmpcstname=tmpcstname.to_frame()
tmpcstname.columns=['counts']
tmpcstname=tmpcstname.reset_index(level=['CustFirstName', 'CustomerID'])
tmpcstname=tmpcstname.drop_duplicates(subset='CustomerID', keep='first')
tmpcstname

     CustomerID CustFirstName  counts
0             1         Aaron    1521
1           125       Abigail     486
2           137       Abigail    1850
3           241       Adriana     121
4           264      Adrienne      17
5           372       Alberto    1844
6           615     Alexandra      60
7           664    Alexandria     102
8           723        Alexis      57
9           726        Alexis    1843
10          782        Alicia     130
11          845        Alison      59
12          905       Allison      13
13          953         Alvin      59
14          973         Alvin    1361
15         1098        Amanda     482
16         1300        Andrew     121
17         1338         Angel      56
18         1423      Angelica     121
19         1452           Ann    1837
20         1568       Annette      59
21         1687       Arianna      57
22         1699       Arianna    1827
23         1917        Audrey      59
24         1941        Austin     132
25         1964        Austin     120
26         2053       Barbara    1846
27         2302         Blake      59
28         2410          Brad      58
29         2425          Brad    1847
30         2482       Brandon     120
31         2779       Bridget     485
32         3000       Caitlin     127
33         3014         Caleb    1833
34         3023         Caleb     123
35         3026         Caleb    1856
36         3241         Carla      16
37         3261        Carlos    1358
38         3374      Caroline      59
39         3541     Cassandra     106
40         3604     Catherine      58
41         3615     Catherine    1838
42         3664        Cedric     117
43         3752       Charles     488
44         3782       Charles      13
45         3987     Christian    1839
46         3989     Christian      58
47         4097       Christy      60
48         4182      Clarence     110
49         4234       Clayton    1359
50         4300          Cody      17
51         4341          Cole    1832
52         4423       Colleen      13
53         4446        Connor      56
54         4588      Cristina    1846
55         4700        Dakota     106
56         4723          Dale     109
57         4941      Danielle      12
58         4942      Danielle    1843
59         4964         Danny     127
60         5061          Dave      59
61         5241           Deb     106
62         5314        Dennis    1833
63         5482         Devin     120
64         5668        Donald     488
65         5676        Donald      58
66         5915         Eddie    1830
67         6000       Eduardo     124
68         6023       Eduardo     134
69         6025       Eduardo      60
70         6133         Edwin      59
71         6150         Edwin    1364
72         6541          Erik     118
73         6629         Ethan     486
74         6640         Ethan      59
75         6641         Ethan     486
76         6664         Ethan     121
77         6748        Evelyn      58
78         6876      Fernando    1847
79         7123     Gabriella    1363
80         7182     Gabrielle     130
81         7230       Garrett    1840
82         7363        Gerald      60
83         7477         Glenn    1356
84         7482         Glenn      59
85         7602         Grant     475
86         7700        Hailey     121
87         7712        Hailey      60
88         7723        Hailey     120
89         7820        Hannah      60
90         7849        Harold    1830
91         7956         Henry     483
92         8203        Isabel    1850
93         8205        Isabel      56
94         8241      Isabella     130
95         8264      Isabella     119
96         8327      Isabelle      57
97         8435          Jack      59
98         8450          Jack    1365
99         8482       Jackson      16
100        8557         Jacob    1843
101        8782         James     101
102        8784         James      60
103        8804         James    1367
104        8929          Jane     484
105        9000         Jared     132
106        9023        Jarrod      13
107        9169           Jay      57
108        9399         Jenny      59
109        9423         Jenny     108
110        9530      Jermaine    1825
111        9541      Jermaine      15
112        9664       Jessica      14
113        9765         JÃ©sus    1838
114        9777          Jill    1355
115        9941          Jodi     106
116        9964           Joe     104
117       10122        Johnny      59
118       10182      Jonathan      13
119       10241      Jonathan      59
120       10366        Jordyn    1362
121       10471          JosÃ©      60
122       10482        Joseph     112
123       10491        Joseph     484
124       10700        Julian     124
125       10723         Julie     121
126       10738         Julie    1841
127       10845       Kaitlyn    1827
128       10856       Kaitlyn      59
129       10964         Karen      58
130       11086          Kate      59
131       11092          Kate    1842
132       11241     Katherine     122
133       11264      Kathleen     129
134       11339       Katrina    1359
135       11446         Keith    1855
136       11464         Keith     485
137       11782        Krista     119
138       11818       Kristen    1840
139       11928    Kristopher      55
140       12065          Kyle    1844
141       12158         Larry      58
142       12172       Latasha     483
143       12300        Lauren     124
144       12419          Levi    1851
145       12423          Levi     130
146       12543          Lisa      59
147       12654         Louis    1352
148       12892          Luke      59
149       12941     Mackenzie     117
150       12964     Mackenzie     122
151       13000       Madison      58
152       13145          Marc     477
153       13380         MarÃ­a    1833
154       13482         Mario     131
155       13507       Marissa      58
156       13615        Martin      58
157       13627        Marvin    1350
158       13700         Mason      13
159       13723         Mason      17
160       13845         Mayra      58
161       13981       Melanie    1834
162       14000       Melanie     107
163       14023       Melinda     102
164       14230  Michael John      59
165       14241       Micheal     132
166       14264       Michele      13
167       14353        Miguel    1852
168       14579       Monique      59
169       14664        Morgan     106
170       14687           Mya      56
171       14707         Nancy    1856
172       14782       Natalie      18
173       14809       Natalie      57
174       14954     Nathaniel    1846
175       15061       Nicolas     490
176       15182          Noah     102
177       15194          Noah      57
178       15300        Olivia     131
179       15302        Olivia      59
180       15308        Olivia    1837
181       15423         Pablo      13
182       15543       Patrick    1360
183       15651         Peter      59
184       15680        Philip    1836
185       15723       Preston     105
186       15941       Randall     122
187       15964         Randy     120
188       16034       Raymond     491
189       16266       Richard      60
190       16269       Richard    1837
191       16281       Richard    1843
192       16482         Robin     117
193       16516        Rodney    1367
194       16870          Ryan    1358
195       16881          Ryan      58
196       16989        Samuel      59
197       16995        Samuel     486
198       17000        Samuel     123
199       17023        Samuel     118
200       17242          Sean    1828
201       17338          Seth      60
202       17541         Shaun     120
203       17596        Sheena    1845
204       17664       Shelley     133
205       17723       Spencer      58
206       17843     Stephanie    1349
207       17953        Steven      56
208       17968        Steven     487
209       18182       Tabitha     118
210       18197       Tabitha    1350
211       18300          Tara      12
212       18322         Tasha     486
213       18568        Thomas      58
214       18569        Thomas    1848
215       18700       Timothy     110
216       18723          Tina     125
217       18917         Trish      58
218       18923        Trisha    1835
219       18941       Tristan      13
220       18964          Troy      16
221       19025        Tyrone      59
222       19158      Victoria    1839
223       19170      Victoria    1364
224       19241      Virginia     110
225       19264        Walter     105
226       19295        Warren     487
227       19410       Whitney      59
228       19482        Willie     133
229       19640        Xavier      59

In [35]:
# perform group by operation to get the counts 
# tmpcstdf = df.groupby(['CustomerID','CustFirstName','CustMiddleInitial','CustLastName'])['SalesID'].nunique()
tmpcstMid = df.groupby(['CustomerID'])['CustMiddleInitial'].value_counts(dropna = False)
tmpcstMid=tmpcstMid.to_frame()
tmpcstMid.columns=['counts']
tmpcstMid=tmpcstMid.reset_index(level=['CustMiddleInitial', 'CustomerID'])
tmpcstMid=tmpcstMid.drop_duplicates(subset='CustomerID', keep='first')
tmpcstMid

     CustomerID CustMiddleInitial  counts
0             1                 4    1521
1           125                 4     486
2           137                 4    1850
3           241                 4     121
4           264                 4      17
5           372                 4    1844
6           615                 4      60
7           664                 4     102
8           723                 4      57
9           726                 4    1843
10          782                 4     130
11          845                 4      59
12          905                 4      13
13          953                 4      59
14          973                 4    1361
15         1098                 4     482
16         1300                 4     121
17         1338                 4      56
18         1423                 4     121
19         1452                 4    1837
20         1568                 4      59
21         1687                 4      57
22         1699                 4    1827
23         1917                 4      59
24         1941                 4     132
25         1964                 4     120
26         2053               NaN    1846
27         2302               NaN      59
28         2410               NaN      58
29         2425                 M    1847
30         2482               NaN     120
31         2779                 E     485
32         3000                 A     127
33         3014               NaN    1833
34         3023               NaN     123
35         3026               NaN    1856
36         3241                 J      16
37         3261               NaN    1358
38         3374               NaN      59
39         3541                 D     106
40         3604               NaN      58
41         3615                 L    1838
42         3664                 W     117
43         3752                 E     488
44         3782                 W      13
45         3987                 J    1839
46         3989                 J      58
47         4097                 A      60
48         4182                 L     110
49         4234               NaN    1359
50         4300               NaN      17
51         4341                 W    1832
52         4423                 L      13
53         4446               NaN      56
54         4588               NaN    1846
55         4700                 A     106
56         4723                 C     109
57         4941                 J      12
58         4942                 J    1843
59         4964                 J     127
60         5061               NaN      59
61         5241               NaN     106
62         5314                 G    1833
63         5482               NaN     120
64         5668               NaN     488
65         5676                 D      58
66         5915               NaN    1830
67         6000               NaN     124
68         6023                 G     134
69         6025                 J      60
70         6133               NaN      59
71         6150                 A    1364
72         6541                 S     118
73         6629               NaN     486
74         6640                 A      59
75         6641                 A     486
76         6664                 M     121
77         6748               NaN      58
78         6876                 J    1847
79         7123               NaN    1363
80         7182               NaN     130
81         7230               NaN    1840
82         7363               NaN      60
83         7477               NaN    1356
84         7482                 A      59
85         7602                 A     475
86         7700                 J     121
87         7712                 M      60
88         7723                 R     120
89         7820                 G      60
90         7849                 D    1830
91         7956                 M     483
92         8203               NaN    1850
93         8205               NaN      56
94         8241               NaN     130
95         8264                 A     119
96         8327                 K      57
97         8435                 L      59
98         8450                 S    1365
99         8482                 A      16
100        8557               NaN    1843
101        8782               NaN     101
102        8784               NaN      60
103        8804                 C    1367
104        8929                 P     484
105        9000                 A     132
106        9023               NaN      13
107        9169               NaN      57
108        9399               NaN      59
109        9423                 S     108
110        9530                 A    1825
111        9541                 J      15
112        9664               NaN      14
113        9765                 K    1838
114        9777               NaN    1355
115        9941               NaN     106
116        9964               NaN     104
117       10122                 G      59
118       10182               NaN      13
119       10241                 J      59
120       10366                 S    1362
121       10471                 G      60
122       10482               NaN     112
123       10491                 J     484
124       10700               NaN     124
125       10723               NaN     121
126       10738                 M    1841
127       10845               NaN    1827
128       10856               NaN      59
129       10964               NaN      58
130       11086               NaN      59
131       11092               NaN    1842
132       11241                 R     122
133       11264                 A     129
134       11339                 M    1359
135       11446               NaN    1855
136       11464                 R     485
137       11782               NaN     119
138       11818                 R    1840
139       11928               NaN      55
140       12065                 T    1844
141       12158                 S      58
142       12172               NaN     483
143       12300                 W     124
144       12419               NaN    1851
145       12423               NaN     130
146       12543                 S      59
147       12654               NaN    1352
148       12892                 J      59
149       12941                 A     117
150       12964                 M     122
151       13000               NaN      58
152       13145               NaN     477
153       13380               NaN    1833
154       13482                 H     131
155       13507               NaN      58
156       13615                 P      58
157       13627                 C    1350
158       13700               NaN      13
159       13723                 M      17
160       13845                 S      58
161       13981                 B    1834
162       14000                 N     107
163       14023                 T     102
164       14230                 R      59
165       14241               NaN     132
166       14264               NaN      13
167       14353               NaN    1852
168       14579               NaN      59
169       14664                 M     106
170       14687               NaN      56
171       14707               NaN    1856
172       14782               NaN      18
173       14809                 E      57
174       14954                 C    1846
175       15061               NaN     490
176       15182               NaN     102
177       15194               NaN      57
178       15300                 D     131
179       15302                 E      59
180       15308                 K    1837
181       15423               NaN      13
182       15543                 L    1360
183       15651                 E      59
184       15680                 M    1836
185       15723               NaN     105
186       15941                 A     122
187       15964               NaN     120
188       16034                 W     491
189       16266                 J      60
190       16269                 L    1837
191       16281                 M    1843
192       16482               NaN     117
193       16516               NaN    1367
194       16870                 C    1358
195       16881                 J      58
196       16989               NaN      59
197       16995               NaN     486
198       17000                 B     123
199       17023                 L     118
200       17242               NaN    1828
201       17338               NaN      60
202       17541                 N     120
203       17596               NaN    1845
204       17664                 N     133
205       17723               NaN      58
206       17843               NaN    1349
207       17953               NaN      56
208       17968                 L     487
209       18182                 A     118
210       18197                 M    1350
211       18300               NaN      12
212       18322               NaN     486
213       18568               NaN      58
214       18569               NaN    1848
215       18700                 L     110
216       18723                 J     125
217       18917                 E      58
218       18923               NaN    1835
219       18941               NaN      13
220       18964               NaN      16
221       19025                 B      59
222       19158               NaN    1839
223       19170               NaN    1364
224       19241               NaN     110
225       19264               NaN     105
226       19295               NaN     487
227       19410                 C      59
228       19482                 R     133
229       19640                 M      59

In [37]:
# perform group by operation to get the counts 
# tmpcstdf = df.groupby(['CustomerID','CustFirstName','CustMiddleInitial','CustLastName'])['SalesID'].nunique()
tmpcstlast = df.groupby(['CustomerID'])['CustLastName'].value_counts(dropna = False)
tmpcstlast=tmpcstlast.to_frame()
tmpcstlast.columns=['counts']
tmpcstlast=tmpcstlast.reset_index(level=['CustLastName', 'CustomerID'])
tmpcstlast=tmpcstlast.drop_duplicates(subset='CustomerID', keep='first')
tmpcstlast

     CustomerID CustLastName  counts
0             1    Alexander    1521
1           125         Wood     486
2           137       Flores    1850
3           241        Vance     121
4           264      JimÃ©nez      17
5           372        Ramos    1844
6           615    Alexander      60
7           664     Peterson     102
8           723       Wilson      57
9           726         Hall    1843
10          782      Chapman     130
11          845          Lal      59
12          905        Allen      13
13          953         Zhao      59
14          973        Zheng    1361
15         1098      Bennett     482
16         1300         Hill     121
17         1338     Phillips      56
18         1423    Alexander     121
19         1452     Gonzalez    1837
20         1568         Hill      59
21         1687   Richardson      57
22         1699         Bell    1827
23         1917         Diaz      59
24         1941        Zhang     132
25         1964          Jai     120
26         2053          Lin    1846
27         2302         Long      59
28         2410         Nath      58
29         2425         Goel    1847
30         2482       Harris     120
31         2779       Chande     485
32         3000       Howard     127
33         3014     Campbell    1833
34         3023           Li     123
35         3026    Patterson    1856
36         3241     Gonzalez      16
37         3261       Howard    1358
38         3374       Butler      59
39         3541        Madan     106
40         3604      Sanders      58
41         3615       Murphy    1838
42         3664           Ma     117
43         3752      Sanders     488
44         3782       Watson      13
45         3987       Garcia    1839
46         3989       Hughes      58
47         4097     Andersen      60
48         4182         Zeng     110
49         4234         Zeng    1359
50         4300         Reed      17
51         4341         Cook    1832
52         4423         Nara      13
53         4446      Edwards      56
54         4588           Xu    1846
55         4700      Russell     106
56         4723         Holt     109
57         4941       Cooper      12
58         4942      Sanders    1843
59         4964      Vazquez     127
60         5061     Richards      59
61         5241       Waldal     106
62         5314           Wu    1833
63         5482       Nelson     120
64         5668        Raman     488
65         5676     Martinez      58
66         5915        Gomez    1830
67         6000       Walker     124
68         6023       Butler     134
69         6025        Brown      60
70         6133           Li      59
71         6150         Deng    1364
72         6541    Gutierrez     118
73         6629        Perry     486
74         6640        Clark      59
75         6641          Lal     486
76         6664       Sharma     121
77         6748        Perez      58
78         6876      Jenkins    1847
79         7123       Rivera    1363
80         7182        Price     130
81         7230       Murphy    1840
82         7363     Martinez      60
83         7477           Lu    1356
84         7482         Zeng      59
85         7602     Andersen     475
86         7700      Coleman     121
87         7712        Lopez      60
88         7723       Rivera     120
89         7820      Jenkins      60
90         7849       Subram    1830
91         7956       Prasad     483
92         8203         Long    1850
93         8205       Powell      56
94         8241     Mitchell     130
95         8264        Evans     119
96         8327    Henderson      57
97         8435        Hayes      59
98         8450      Richins    1365
99         8482       Foster      16
100        8557     Martinez    1843
101        8782        Kumar     101
102        8784     Mitchell      60
103        8804        Evans    1367
104        8929        Greer     484
105        9000         Gray     132
106        9023         Rana      13
107        9169      Carlson      57
108        9399    Zimmerman      59
109        9423        Liang     108
110        9530       Kapoor    1825
111        9541        Perez      15
112        9664    Rodriguez      14
113        9765        Munoz    1838
114        9777        Gomez    1355
115        9941         Deng     106
116        9964    Gutierrez     104
117       10122        Kumar      59
118       10182       Butler      13
119       10241    Hernandez      59
120       10366      Coleman    1362
121       10471        Lopez      60
122       10482        White     112
123       10491      Cantoni     484
124       10700      Jenkins     124
125       10723          Jai     121
126       10738          Luo    1841
127       10845        Allen    1827
128       10856       Harris      59
129       10964        Huang      58
130       11086       Becker      59
131       11092         Raje    1842
132       11241         Cook     122
133       11264        Rubio     129
134       11339       Sharma    1359
135       11446          Lal    1855
136       11464          Pal     485
137       11782         Gill     119
138       11818           Li    1840
139       11928     Martinez      55
140       12065        Young    1844
141       12158        Gomez      58
142       12172       Suarez     483
143       12300       Cooper     124
144       12419     Gonzalez    1851
145       12423       Prasad     130
146       12543         Chen      59
147       12654           Hu    1352
148       12892      Simmons      59
149       12941        Adams     117
150       12964      Ramirez     122
151       13000       Foster      58
152       13145       Romero     477
153       13380       Flores    1833
154       13482          Rai     131
155       13507        Price      58
156       13615        Patel      58
157       13627        Gomez    1350
158       13700       Wright      13
159       13723         Cook      17
160       13845      Sanchez      58
161       13981      Russell    1834
162       14000    Alexander     107
163       14023      Jimenez     102
164       14230       Troyer      59
165       14241      Vazquez     132
166       14264         Raji      13
167       14353     Gonzalez    1852
168       14579       Torres      59
169       14664         Hill     106
170       14687      Coleman      56
171       14707     Buchanan    1856
172       14782         Reed      18
173       14809     Williams      57
174       14954       Howard    1846
175       15061         Raje     490
176       15182       Bryant     102
177       15194        Jones      57
178       15300      Bennett     131
179       15302       Howard      59
180       15308          Cox    1837
181       15423  Rovira Diez      13
182       15543      Sanders    1360
183       15651        Black      59
184       15680    Gutierrez    1836
185       15723        Perez     105
186       15941         Ruiz     122
187       15964        Zhang     120
188       16034        Madan     491
189       16266     Martinez      60
190       16269       Cooper    1837
191       16281        Brown    1843
192       16482       Ortega     117
193       16516         Sanz    1367
194       16870        Davis    1358
195       16881    Alexander      58
196       16989       Sharma      59
197       16995        Young     486
198       17000     Johnston     123
199       17023     Robinson     118
200       17242        Green    1828
201       17338      Bennett      60
202       17541     Andersen     120
203       17596       Chande    1845
204       17664         Dyck     133
205       17723      Bennett      58
206       17843    Alexander    1349
207       17953       Watson      56
208       17968     Peterson     487
209       18182     Gonzalez     118
210       18197    Rodriguez    1350
211       18300          Xie      12
212       18322         Yuan     486
213       18568           Li      58
214       18569     Martinez    1848
215       18700      Sanders     110
216       18723        Lopez     125
217       18917     Pederson      58
218       18923          Sun    1835
219       18941       Butler      13
220       18964      Chandra      16
221       19025         Ruiz      59
222       19158       Powell    1839
223       19170     Williams    1364
224       19241    Rodriguez     110
225       19264      Jimenez     105
226       19295         Zhao     487
227       19410      Sanchez      59
228       19482          Gao     133
229       19640        Smith      59

In [38]:
del tmpcstname['counts']
del tmpcstMid['counts']
del tmpcstlast['counts']

In [40]:
tmpcstdf = pd.merge(tmpcstname, tmpcstMid, on=['CustomerID'])
cstdf = pd.merge(tmpcstdf, tmpcstlast, on=['CustomerID'])

In [41]:
cstdf

     CustomerID CustFirstName CustMiddleInitial CustLastName
0             1         Aaron                 4    Alexander
1           125       Abigail                 4         Wood
2           137       Abigail                 4       Flores
3           241       Adriana                 4        Vance
4           264      Adrienne                 4      JimÃ©nez
5           372       Alberto                 4        Ramos
6           615     Alexandra                 4    Alexander
7           664    Alexandria                 4     Peterson
8           723        Alexis                 4       Wilson
9           726        Alexis                 4         Hall
10          782        Alicia                 4      Chapman
11          845        Alison                 4          Lal
12          905       Allison                 4        Allen
13          953         Alvin                 4         Zhao
14          973         Alvin                 4        Zheng
15         1098        Amanda                 4      Bennett
16         1300        Andrew                 4         Hill
17         1338         Angel                 4     Phillips
18         1423      Angelica                 4    Alexander
19         1452           Ann                 4     Gonzalez
20         1568       Annette                 4         Hill
21         1687       Arianna                 4   Richardson
22         1699       Arianna                 4         Bell
23         1917        Audrey                 4         Diaz
24         1941        Austin                 4        Zhang
25         1964        Austin                 4          Jai
26         2053       Barbara               NaN          Lin
27         2302         Blake               NaN         Long
28         2410          Brad               NaN         Nath
29         2425          Brad                 M         Goel
30         2482       Brandon               NaN       Harris
31         2779       Bridget                 E       Chande
32         3000       Caitlin                 A       Howard
33         3014         Caleb               NaN     Campbell
34         3023         Caleb               NaN           Li
35         3026         Caleb               NaN    Patterson
36         3241         Carla                 J     Gonzalez
37         3261        Carlos               NaN       Howard
38         3374      Caroline               NaN       Butler
39         3541     Cassandra                 D        Madan
40         3604     Catherine               NaN      Sanders
41         3615     Catherine                 L       Murphy
42         3664        Cedric                 W           Ma
43         3752       Charles                 E      Sanders
44         3782       Charles                 W       Watson
45         3987     Christian                 J       Garcia
46         3989     Christian                 J       Hughes
47         4097       Christy                 A     Andersen
48         4182      Clarence                 L         Zeng
49         4234       Clayton               NaN         Zeng
50         4300          Cody               NaN         Reed
51         4341          Cole                 W         Cook
52         4423       Colleen                 L         Nara
53         4446        Connor               NaN      Edwards
54         4588      Cristina               NaN           Xu
55         4700        Dakota                 A      Russell
56         4723          Dale                 C         Holt
57         4941      Danielle                 J       Cooper
58         4942      Danielle                 J      Sanders
59         4964         Danny                 J      Vazquez
60         5061          Dave               NaN     Richards
61         5241           Deb               NaN       Waldal
62         5314        Dennis                 G           Wu
63         5482         Devin               NaN       Nelson
64         5668        Donald               NaN        Raman
65         5676        Donald                 D     Martinez
66         5915         Eddie               NaN        Gomez
67         6000       Eduardo               NaN       Walker
68         6023       Eduardo                 G       Butler
69         6025       Eduardo                 J        Brown
70         6133         Edwin               NaN           Li
71         6150         Edwin                 A         Deng
72         6541          Erik                 S    Gutierrez
73         6629         Ethan               NaN        Perry
74         6640         Ethan                 A        Clark
75         6641         Ethan                 A          Lal
76         6664         Ethan                 M       Sharma
77         6748        Evelyn               NaN        Perez
78         6876      Fernando                 J      Jenkins
79         7123     Gabriella               NaN       Rivera
80         7182     Gabrielle               NaN        Price
81         7230       Garrett               NaN       Murphy
82         7363        Gerald               NaN     Martinez
83         7477         Glenn               NaN           Lu
84         7482         Glenn                 A         Zeng
85         7602         Grant                 A     Andersen
86         7700        Hailey                 J      Coleman
87         7712        Hailey                 M        Lopez
88         7723        Hailey                 R       Rivera
89         7820        Hannah                 G      Jenkins
90         7849        Harold                 D       Subram
91         7956         Henry                 M       Prasad
92         8203        Isabel               NaN         Long
93         8205        Isabel               NaN       Powell
94         8241      Isabella               NaN     Mitchell
95         8264      Isabella                 A        Evans
96         8327      Isabelle                 K    Henderson
97         8435          Jack                 L        Hayes
98         8450          Jack                 S      Richins
99         8482       Jackson                 A       Foster
100        8557         Jacob               NaN     Martinez
101        8782         James               NaN        Kumar
102        8784         James               NaN     Mitchell
103        8804         James                 C        Evans
104        8929          Jane                 P        Greer
105        9000         Jared                 A         Gray
106        9023        Jarrod               NaN         Rana
107        9169           Jay               NaN      Carlson
108        9399         Jenny               NaN    Zimmerman
109        9423         Jenny                 S        Liang
110        9530      Jermaine                 A       Kapoor
111        9541      Jermaine                 J        Perez
112        9664       Jessica               NaN    Rodriguez
113        9765         JÃ©sus                 K        Munoz
114        9777          Jill               NaN        Gomez
115        9941          Jodi               NaN         Deng
116        9964           Joe               NaN    Gutierrez
117       10122        Johnny                 G        Kumar
118       10182      Jonathan               NaN       Butler
119       10241      Jonathan                 J    Hernandez
120       10366        Jordyn                 S      Coleman
121       10471          JosÃ©                 G        Lopez
122       10482        Joseph               NaN        White
123       10491        Joseph                 J      Cantoni
124       10700        Julian               NaN      Jenkins
125       10723         Julie               NaN          Jai
126       10738         Julie                 M          Luo
127       10845       Kaitlyn               NaN        Allen
128       10856       Kaitlyn               NaN       Harris
129       10964         Karen               NaN        Huang
130       11086          Kate               NaN       Becker
131       11092          Kate               NaN         Raje
132       11241     Katherine                 R         Cook
133       11264      Kathleen                 A        Rubio
134       11339       Katrina                 M       Sharma
135       11446         Keith               NaN          Lal
136       11464         Keith                 R          Pal
137       11782        Krista               NaN         Gill
138       11818       Kristen                 R           Li
139       11928    Kristopher               NaN     Martinez
140       12065          Kyle                 T        Young
141       12158         Larry                 S        Gomez
142       12172       Latasha               NaN       Suarez
143       12300        Lauren                 W       Cooper
144       12419          Levi               NaN     Gonzalez
145       12423          Levi               NaN       Prasad
146       12543          Lisa                 S         Chen
147       12654         Louis               NaN           Hu
148       12892          Luke                 J      Simmons
149       12941     Mackenzie                 A        Adams
150       12964     Mackenzie                 M      Ramirez
151       13000       Madison               NaN       Foster
152       13145          Marc               NaN       Romero
153       13380         MarÃ­a               NaN       Flores
154       13482         Mario                 H          Rai
155       13507       Marissa               NaN        Price
156       13615        Martin                 P        Patel
157       13627        Marvin                 C        Gomez
158       13700         Mason               NaN       Wright
159       13723         Mason                 M         Cook
160       13845         Mayra                 S      Sanchez
161       13981       Melanie                 B      Russell
162       14000       Melanie                 N    Alexander
163       14023       Melinda                 T      Jimenez
164       14230  Michael John                 R       Troyer
165       14241       Micheal               NaN      Vazquez
166       14264       Michele               NaN         Raji
167       14353        Miguel               NaN     Gonzalez
168       14579       Monique               NaN       Torres
169       14664        Morgan                 M         Hill
170       14687           Mya               NaN      Coleman
171       14707         Nancy               NaN     Buchanan
172       14782       Natalie               NaN         Reed
173       14809       Natalie                 E     Williams
174       14954     Nathaniel                 C       Howard
175       15061       Nicolas               NaN         Raje
176       15182          Noah               NaN       Bryant
177       15194          Noah               NaN        Jones
178       15300        Olivia                 D      Bennett
179       15302        Olivia                 E       Howard
180       15308        Olivia                 K          Cox
181       15423         Pablo               NaN  Rovira Diez
182       15543       Patrick                 L      Sanders
183       15651         Peter                 E        Black
184       15680        Philip                 M    Gutierrez
185       15723       Preston               NaN        Perez
186       15941       Randall                 A         Ruiz
187       15964         Randy               NaN        Zhang
188       16034       Raymond                 W        Madan
189       16266       Richard                 J     Martinez
190       16269       Richard                 L       Cooper
191       16281       Richard                 M        Brown
192       16482         Robin               NaN       Ortega
193       16516        Rodney               NaN         Sanz
194       16870          Ryan                 C        Davis
195       16881          Ryan                 J    Alexander
196       16989        Samuel               NaN       Sharma
197       16995        Samuel               NaN        Young
198       17000        Samuel                 B     Johnston
199       17023        Samuel                 L     Robinson
200       17242          Sean               NaN        Green
201       17338          Seth               NaN      Bennett
202       17541         Shaun                 N     Andersen
203       17596        Sheena               NaN       Chande
204       17664       Shelley                 N         Dyck
205       17723       Spencer               NaN      Bennett
206       17843     Stephanie               NaN    Alexander
207       17953        Steven               NaN       Watson
208       17968        Steven                 L     Peterson
209       18182       Tabitha                 A     Gonzalez
210       18197       Tabitha                 M    Rodriguez
211       18300          Tara               NaN          Xie
212       18322         Tasha               NaN         Yuan
213       18568        Thomas               NaN           Li
214       18569        Thomas               NaN     Martinez
215       18700       Timothy                 L      Sanders
216       18723          Tina                 J        Lopez
217       18917         Trish                 E     Pederson
218       18923        Trisha               NaN          Sun
219       18941       Tristan               NaN       Butler
220       18964          Troy               NaN      Chandra
221       19025        Tyrone                 B         Ruiz
222       19158      Victoria               NaN       Powell
223       19170      Victoria               NaN     Williams
224       19241      Virginia               NaN    Rodriguez
225       19264        Walter               NaN      Jimenez
226       19295        Warren               NaN         Zhao
227       19410       Whitney                 C      Sanchez
228       19482        Willie                 R          Gao
229       19640        Xavier                 M        Smith