# Importing the required packages

In [547]:
# import the necessary packages
import pandas as pd
import mysql.connector
print("packages imported")

packages imported

# Extracting the raw data

In [548]:
# make a connection to mysql database for extracting the raw data
mydb = mysql.connector.connect(host='localhost', database='salesdb', user='root', password='Csoares#12')
df = pd.read_sql('SELECT * FROM sales_data_etl', con=mydb)

In [549]:
# Set the values to display all the counts in one output cell
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.options.display.float_format = "{:,.2f}".format

In [550]:
df.head()

   SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial EmpLastName  ProductID      ProductName  Quantity    Price
0        4        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire       437  24.9900
1        9           1         Aaron                 4    Alexander           1      Abraham                f      Bennet          1  Adjustable Race        10  1.6000$
2       20        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire       437  24.9900
3       25           1         Aaron                 4    Alexander           1      Abraham                f      Bennet          1  Adjustable Race        26  1.6000$
4       33       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26    Flat Washer 4       530   0.0000

In [551]:
# check the shape of the data
df.shape

(129469, 13)

In [552]:
df.dtypes

SalesID               int64
CustomerID            int64
CustFirstName        object
CustMiddleInitial    object
CustLastName         object
EmployeeID            int64
EmpFirstName         object
EmpMiddleInitial     object
EmpLastName          object
ProductID             int64
ProductName          object
Quantity              int64
Price                object
dtype: object

# Perform the required Transformations

In [553]:
# calculate the frequency counts of each value in CustMiddleInitial column
df['CustMiddleInitial'].value_counts(dropna=False)

NaN    57245
4      14394
M      11044
J       6783
C       6089
L       5932
A       5314
K       3732
S       3128
R       2759
W       2577
G       2146
D       2125
B       2016
T       1946
E       1206
P        542
N        360
H        131
Name: CustMiddleInitial, dtype: int64

In [554]:
df['CustMiddleInitial'].value_counts()['4']

14394

In [555]:
# replace the value 4 in CustMiddleInitial column with None
df.loc[df.CustMiddleInitial == "4", "CustMiddleInitial"] = None

In [556]:
df['CustMiddleInitial'].value_counts(dropna=False)

NaN    71639
M      11044
J       6783
C       6089
L       5932
A       5314
K       3732
S       3128
R       2759
W       2577
G       2146
D       2125
B       2016
T       1946
E       1206
P        542
N        360
H        131
Name: CustMiddleInitial, dtype: int64

In [557]:
df.head()

   SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial EmpLastName  ProductID      ProductName  Quantity    Price
0        4        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire       437  24.9900
1        9           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1  Adjustable Race        10  1.6000$
2       20        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire       437  24.9900
3       25           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1  Adjustable Race        26  1.6000$
4       33       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26    Flat Washer 4       530   0.0000

In [558]:
# calculate frequency of values in the Price Column
df['Price'].value_counts(dropna=False)

0.0000        10013
742.3500       5585
1457.9900      4055
24.9900        3547
337.2200       3493
91.4900        2035
72.8000        2034
44.9900        2033
348.7600       2033
3399.9900      2030
594.8300       2030
75.4000        2025
27.1200        2025
34.2000        2024
177.6000       2023
3374.9900      2023
39.1400        2021
636.8000       2018
69.9900        2017
85.5650        2016
34.9900        2016
418.4000       2013
88.0000        2013
85.6000        2013
306.0000       2010
1700.9900      2003
53.9900        1968
152.4000       1964
80.9900        1956
64.8000        1913
1120.4900      1907
63.5000        1901
169.6000       1898
418.8000       1897
8.9900         1896
333.4200       1895
843.2000       1890
1079.9900      1866
121.4600$      1850
472.8000$      1844
196.4000$      1843
594.8300$      1837
74.9900        1833
389.6000$      1827
564.0000€      1825
1364.5000      1534
1349.6000      1527
1003.9100      1525
1.6000$        1521
133.3400       1519
548.4000       1518
829.8000       1465
2443.3500€     1364
101.2400$      1361
441.6000       1360
337.2200$       541
144.0000        509
1214.8500       503
1431.5000       501
249.7900        501
21.9800         501
183.2000        499
539.9900        497
910.8000        490
2294.9900€      486
1364.5000$      486
564.9900        485
90.8000€        475
196.4000        178
594.8300€       177
389.6000        176
101.2400        172
441.6000€       165
564.0000        134
0.0000€         132
8.9900$         132
333.4200$       130
121.4600€       129
418.8000€       127
74.9900€        122
843.2000$       121
64.8000$        121
169.6000$       121
1120.4900$      120
63.5000€        119
472.8000€       118
2443.3500       106
1079.9900$      102
2443.3500$       60
564.0000$        59
53.9900$         59
80.9900$         59
1079.9900€       59
472.8000         58
121.4600         58
152.4000$        57
829.8000$        57
74.9900$         56
2294.9900$       17
1700.9900€       16
90.8000          13
564.9900$        13
Name: Price, dtype: int64

In [559]:
# replace the $ and € symbol with a blank character in the Price column to maintain Consistency
df['Price'] = df['Price'].str.replace(r'[^\d.]+','')

In [560]:
# check the frequency of Price Value to see if the currency characters have been removed
df['Price'].value_counts(dropna=False)

0.0000       10145
742.3500      5585
1457.9900     4055
594.8300      4044
337.2200      4034
24.9900       3547
121.4600      2037
91.4900       2035
64.8000       2034
72.8000       2034
44.9900       2033
348.7600      2033
3399.9900     2030
8.9900        2028
53.9900       2027
1120.4900     2027
1079.9900     2027
27.1200       2025
333.4200      2025
75.4000       2025
418.8000      2024
34.2000       2024
3374.9900     2023
177.6000      2023
39.1400       2021
152.4000      2021
196.4000      2021
1364.5000     2020
63.5000       2020
472.8000      2020
1700.9900     2019
169.6000      2019
636.8000      2018
564.0000      2018
69.9900       2017
34.9900       2016
85.5650       2016
80.9900       2015
85.6000       2013
418.4000      2013
88.0000       2013
843.2000      2011
74.9900       2011
306.0000      2010
389.6000      2003
101.2400      1533
2443.3500     1530
1349.6000     1527
1003.9100     1525
441.6000      1525
829.8000      1522
1.6000        1521
133.3400      1519
548.4000      1518
144.0000       509
2294.9900      503
1214.8500      503
1431.5000      501
249.7900       501
21.9800        501
183.2000       499
564.9900       498
539.9900       497
910.8000       490
90.8000        488
Name: Price, dtype: int64

In [561]:
df.head()

   SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial EmpLastName  ProductID      ProductName  Quantity    Price
0        4        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire       437  24.9900
1        9           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1  Adjustable Race        10   1.6000
2       20        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire       437  24.9900
3       25           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1  Adjustable Race        26   1.6000
4       33       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26    Flat Washer 4       530   0.0000

In [562]:
df['Quantity'].value_counts(dropna=False)

530    2037
903    2037
467    2036
450    2035
13     2034
857    2033
840    2033
590    2032
763    2032
780    2030
513    2029
340    2029
153    2029
217    2028
810    2027
560    2025
403    2025
920    2025
310    2024
30     2024
280    2023
123    2023
263    2023
420    2021
170    2021
60     2021
967    2021
577    2020
873    2020
607    2019
653    2018
77     2018
90     2017
373    2017
827    2016
717    2016
327    2015
950    2015
623    2013
700    2013
107    2013
357    2011
200    2011
670    2003
500    1533
297    1530
483    1528
890    1528
250    1527
437    1527
547    1527
47     1525
733    1525
390    1525
797    1524
140    1523
750    1522
937    1522
187    1519
640    1518
983    1517
11     1517
687    1515
233    1515
543     509
43      507
980     503
793     503
293     503
480     502
887     501
730     501
933     501
387     499
137     499
230     499
433     498
997     498
247     498
497     497
747     495
183     495
683     490
637     488
10        1
179       1
195       1
26        1
Name: Quantity, dtype: int64

In [563]:
df['ProductID'].value_counts(dropna=False)

399    2037
26     2037
467    2036
450    2035
13     2034
43     2034
353    2033
336    2033
86     2032
259    2032
276    2030
153    2030
340    2029
9      2029
217    2028
293    2027
306    2027
56     2025
416    2025
403    2025
310    2024
30     2024
123    2023
280    2023
263    2023
170    2021
463    2021
420    2021
60     2021
369    2020
433    2020
73     2020
103    2019
77     2018
149    2018
90     2017
373    2017
323    2016
213    2016
327    2015
446    2015
107    2013
119    2013
196    2013
357    2011
200    2011
183    2010
166    2003
500    1533
297    1530
483    1528
386    1528
250    1527
437    1527
47     1525
229    1525
390    1525
246    1522
140    1522
1      1521
187    1519
136    1518
479    1517
233    1515
39      509
289     503
476     503
480     502
226     501
429     501
383     501
137     499
230     499
387     499
493     498
247     498
497     497
243     495
179     490
133     488
Name: ProductID, dtype: int64

In [564]:
df['EmployeeID'].value_counts(dropna=False)

1     12683
7      8104
15     7598
8      6564
22     6555
6      6091
17     6074
4      6071
12     6069
10     6064
5      6058
9      6058
21     5577
20     5576
2      5556
13     5071
14     5052
3      5037
16     4517
18     3556
11     3023
19     2515
Name: EmployeeID, dtype: int64

In [566]:
df1 = df['CustomerID'].value_counts(dropna=False)

In [568]:
df1.to_frame()

       CustomerID
14707        1856
3026         1856
11446        1855
14353        1852
12419        1851
8203         1850
137          1850
18569        1848
6876         1847
2425         1847
14954        1846
2053         1846
4588         1846
17596        1845
12065        1844
372          1844
726          1843
4942         1843
8557         1843
16281        1843
11092        1842
10738        1841
7230         1840
11818        1840
19158        1839
3987         1839
3615         1838
9765         1838
1452         1837
15308        1837
16269        1837
15680        1836
18923        1835
13981        1834
13380        1833
3014         1833
5314         1833
4341         1832
5915         1830
7849         1830
17242        1828
1699         1827
10845        1827
9530         1825
1            1521
8804         1367
16516        1367
8450         1365
6150         1364
19170        1364
7123         1363
10366        1362
973          1361
15543        1360
4234         1359
11339        1359
3261         1358
16870        1358
7477         1356
9777         1355
12654        1352
18197        1350
13627        1350
17843        1349
16034         491
15061         490
3752          488
5668          488
19295         487
17968         487
18322         486
6629          486
125           486
16995         486
6641          486
2779          485
11464         485
10491         484
8929          484
12172         483
7956          483
1098          482
13145         477
7602          475
6023          134
17664         133
19482         133
9000          132
14241         132
1941          132
13482         131
15300         131
8241          130
12423         130
7182          130
782           130
11264         129
3000          127
4964          127
18723         125
10700         124
6000          124
12300         124
3023          123
17000         123
12964         122
15941         122
11241         122
6664          121
1300          121
1423          121
241           121
10723         121
7700          121
5482          120
7723          120
15964         120
2482          120
17541         120
1964          120
11782         119
8264          119
6541          118
17023         118
18182         118
16482         117
12941         117
3664          117
10482         112
4182          110
19241         110
18700         110
4723          109
9423          108
14000         107
9941          106
14664         106
3541          106
4700          106
5241          106
15723         105
19264         105
9964          104
14023         102
664           102
15182         102
8782          101
615            60
7712           60
10471          60
6025           60
17338          60
7363           60
16266          60
4097           60
8784           60
7820           60
10241          59
845            59
11086          59
15302          59
5061           59
2302           59
10122          59
12892          59
14579          59
12543          59
9399           59
6640           59
19640          59
3374           59
10856          59
953            59
7482           59
15651          59
8435           59
19410          59
1568           59
19025          59
16989          59
14230          59
1917           59
6133           59
18917          58
10964          58
12158          58
13845          58
5676           58
3989           58
13000          58
17723          58
16881          58
2410           58
13507          58
13615          58
18568          58
3604           58
6748           58
8327           57
15194          57
9169           57
1687           57
723            57
14809          57
4446           56
1338           56
14687          56
17953          56
8205           56
11928          55
14782          18
264            17
4300           17
13723          17
3241           16
8482           16
18964          16
9541           15
9664           14
10182          13
3782           13
13700          13
4423           13
905            13
18941          13
9023           13
14264          13
15423          13
4941           12
18300          12

In [ ]:
df.head()

# Split the dataframe into multiple dataframes

creation of Customer data frame

In [582]:
# perform group by operation to get the counts 
# tmpcstdf = df.groupby(['CustomerID','CustFirstName','CustMiddleInitial','CustLastName'])['SalesID'].nunique()
tmpcstdf = df.groupby(['CustomerID','CustFirstName','CustMiddleInitial','CustLastName'])

In [583]:
tmpcstdf = tmpcstdf.first()

In [584]:
tmpcstdf

                                                         SalesID  EmployeeID EmpFirstName EmpMiddleInitial     EmpLastName  ProductID                     ProductName  Quantity      Price
CustomerID CustFirstName CustMiddleInitial CustLastName
2425       Brad          M                 Goel            11652          12     Charlene                o        Locksley        336   ML Mountain Frame - Black, 44       840   348.7600
2779       Bridget       E                 Chande          13758          19      Meander                m           Smith        433                LL Mountain Tire       433    24.9900
3000       Caitlin       A                 Howard             41           7     Marjorie                r           Green         30                   Flat Washer 7        30   418.8000
3241       Carla         J                 Gonzalez          166           1      Abraham                f          Bennet        230         LL Road Frame - Red, 44       230   337.2200
3541       Cassandra     D                 Madan             131           3       Cheryl                a          Carson        233         LL Road Frame - Red, 58       233   337.2200
3615       Catherine     L                 Murphy          11664           7     Marjorie                r           Green         30                   Flat Washer 7        30   418.8000
3664       Cedric        W                 Ma                101          22      Johnson                h           White        323             LL Road Front Wheel       827    85.5650
3752       Charles       E                 Sanders         13741          13      Stearns                a      MacFeather        429   LL Mountain Frame - Black, 42       933   249.7900
3782       Charles       W                 Watson           3064          19      Meander                m           Smith        433                LL Mountain Tire       433    24.9900
3987       Christian     J                 Garcia          11637           9         Burt                r      Gringlesby        103             Thin-Jam Lock Nut 1       607   169.6000
3989       Christian     J                 Hughes           7907           2     Reginald                l  Blotchet-Halls         73                      Hex Nut 15       577   472.8000
4097       Christy       A                 Andersen         7892          18         Anne                i          Ringer        340    ML Road Frame-W - Yellow, 44       340   594.8300
4182       Clarence      L                 Zeng                4           1      Abraham                f          Bennet        437                    ML Road Tire       437    24.9900
4341       Cole          W                 Cook            11613          16       Sylvia                a        Panteley        200                          Spokes       200   843.2000
4423       Colleen       L                 Nara             3077          16       Sylvia                a        Panteley        133                     Lock Nut 21       637    90.8000
4700       Dakota        A                 Russell           124           1      Abraham                f          Bennet         47              Thin-Jam Hex Nut 4        47   441.6000
4723       Dale          C                 Holt               94          19      Meander                m           Smith        136                     Lock Nut 15       640   548.4000
4941       Danielle      J                 Cooper           3116          17       Albert                i          Ringer        247  HL Mountain Frame - Silver, 46       247  1364.5000
4942       Danielle      J                 Sanders         11670           8  Morningstar                r          Greene        123                      Lock Nut 9       123   177.6000
4964       Danny         J                 Vazquez            34          12     Charlene                o        Locksley        336   ML Mountain Frame - Black, 44       840   348.7600
5314       Dennis        G                 Wu              11643          10       Sheryl                u          Hunter        196                 LL Spindle/Axle       700   418.4000
5676       Donald        D                 Martinez         7916           4       Michel                e        DeFrance        213         Sport-100 Helmet, Black       717    34.9900
6023       Eduardo       G                 Butler             43           9         Burt                r      Gringlesby        149                   Lock Washer 7       653   564.0000
6025       Eduardo       J                 Brown            7902          17       Albert                i          Ringer        500               ML Bottom Bracket       500   101.2400
6150       Edwin         A                 Deng            11619          21         Dirk                t        Stringer        297                Road-250 Red, 58       297  2443.3500
6541       Erik          S                 Gutierrez          96          10       Sheryl                u          Hunter        263                Road-450 Red, 52       263  1457.9900
6640       Ethan         A                 Clark            7921          15      Michael                '         O'Leary        293          Mountain-300 Black, 48       797  1079.9900
6641       Ethan         A                 Lal             13778          11        Livia                a          Karsen        289          Mountain-200 Black, 46       793  2294.9900
6664       Ethan         M                 Sharma            133           6          Ann                u            Dull        353       Headlights - Weatherproof       857    44.9900
6876       Fernando      J                 Jenkins         11630           7     Marjorie                r           Green        467         Touring-3000 Yellow, 50       467   742.3500
7482       Glenn         A                 Zeng             7873           1      Abraham                f          Bennet         47              Thin-Jam Hex Nut 4        47   441.6000
7602       Grant         A                 Andersen        13768          16       Sylvia                a        Panteley        133                     Lock Nut 21       637    90.8000
7700       Hailey        J                 Coleman           207           8  Morningstar                r          Greene         77                  Handlebar Tube        77   636.8000
7712       Hailey        M                 Lopez            7911          19      Meander                m           Smith        136                     Lock Nut 15       640   548.4000
7723       Hailey        R                 Rivera            126           3       Cheryl                a          Carson        166                   Metal Sheet 6       670   389.6000
7820       Hannah        G                 Jenkins          7896          12     Charlene                o        Locksley        403     LL Touring Frame - Blue, 62       403   333.4200
7849       Harold        D                 Subram          11660           1      Abraham                f          Bennet        463           Touring-3000 Blue, 54       967   742.3500
7956       Henry         M                 Prasad          13804           1      Abraham                f          Bennet        230         LL Road Frame - Red, 44       230   337.2200
8264       Isabella      A                 Evans              15          22      Johnson                h           White        369                 Classic Vest, S       873    63.5000
8327       Isabelle      K                 Henderson        7930          17       Albert                i          Ringer        433                LL Mountain Tire       937    24.9900
8435       Jack          L                 Hayes            7915          10       Sheryl                u          Hunter        196                 LL Spindle/Axle       700   418.4000
8450       Jack          S                 Richins         11655          16       Sylvia                a        Panteley        386  Short-Sleeve Classic Jersey, S       890    53.9900
8482       Jackson       A                 Foster            170          20         Dean                t        Straight        480           Road-350-W Yellow, 44       480  1700.9900
8804       James         C                 Evans           11693           1      Abraham                f          Bennet        483           Touring-3000 Blue, 44       483   742.3500
8929       Jane          P                 Greer           13735          17       Albert                i          Ringer        226         HL Road Frame - Red, 56       730  1431.5000
9000       Jared         A                 Gray               38          21         Dirk                t        Stringer         90          External Lock Washer 2        90     0.0000
9423       Jenny         S                 Liang               8          20         Dean                t        Straight        183                     LL Road Rim       687   306.0000
9530       Jermaine      A                 Kapoor          11640           9         Burt                r      Gringlesby        149                   Lock Washer 7       653   564.0000
9541       Jermaine      J                 Perez             163          17       Albert                i          Ringer        293          Mountain-300 Black, 48       293  1079.9900
9765       Jésus         K                 Munoz           11621           5        Innes                e    del Castillo        327    ML Road Frame-W - Yellow, 38       327   594.8300
10122      Johnny        G                 Kumar            7924          12     Charlene                o        Locksley        336   ML Mountain Frame - Black, 44       840   348.7600
10241      Jonathan      J                 Hernandez        7936           7     Marjorie                r           Green         30                   Flat Washer 7        30   418.8000
10366      Jordyn        S                 Coleman         11616          20         Dean                t        Straight        250   HL Mountain Frame - Black, 48       250  1349.6000
10471      José          G                 Lopez            7910           2     Reginald                l  Blotchet-Halls        119                     Lock Nut 16       623    88.0000
10491      Joseph        J                 Cantoni         13762          14      Heather                c        McBadden        497          Mountain-500 Black, 48       497   539.9900
10738      Julie         M                 Luo             11651          22      Johnson                h           White        323             LL Road Front Wheel       827    85.5650
11241      Katherine     R                 Cook               10          11        Livia                a          Karsen        310                      LL Headset       310    34.2000
11264      Kathleen      A                 Rubio              31           6          Ann                u            Dull        399                 Rear Derailleur       903   121.4600
11339      Katrina       M                 Sharma          11646          14      Heather                c        McBadden        246  HL Mountain Frame - Silver, 48       750  1364.5000
11464      Keith         R                 Pal             13791           8  Morningstar                r          Greene        493         Mountain-500 Silver, 52       997   564.9900
11818      Kristen       R                 Li              11636          15      Michael                '         O'Leary         86          External Lock Washer 7       590     0.0000
12065      Kyle          T                 Young           11657           1      Abraham                f          Bennet        416             LL Road Seat/Saddle       920    27.1200
12158      Larry         S                 Gomez            7919           4       Michel                e        DeFrance        259                Road-450 Red, 58       763  1457.9900
12300      Lauren        W                 Cooper              3           8  Morningstar                r          Greene        123                      Lock Nut 9       123   177.6000
12543      Lisa          S                 Chen             7900           7     Marjorie                r           Green        467         Touring-3000 Yellow, 50       467   742.3500
12892      Luke          J                 Simmons          7886          20         Dean                t        Straight        250   HL Mountain Frame - Black, 48       250  1349.6000
12941      Mackenzie     A                 Adams              93           5        Innes                e    del Castillo        327    ML Road Frame-W - Yellow, 38       327   594.8300
12964      Mackenzie     M                 Ramirez           130           1      Abraham                f          Bennet        416             LL Road Seat/Saddle       920    27.1200
13482      Mario         H                 Rai                33           1      Abraham                f          Bennet         26                   Flat Washer 4       530     0.0000
13615      Martin        P                 Patel            7890          11        Livia                a          Karsen        310                      LL Headset       310    34.2000
13627      Marvin        C                 Gomez           11642          20         Dean                t        Straight        183                     LL Road Rim       687   306.0000
13723      Mason         M                 Cook              174          17       Albert                i          Ringer        226         HL Road Frame - Red, 56       730  1431.5000
13845      Mayra         S                 Sanchez          7928           6          Ann                u            Dull        399                 Rear Derailleur       903   121.4600
13981      Melanie       B                 Russell         11618           4       Michel                e        DeFrance        280          Mountain-100 Black, 38       280  3374.9900
14000      Melanie       N                 Alexander         204           2     Reginald                l  Blotchet-Halls        140                       Lock Ring       140   829.8000
14023      Melinda       T                 Jimenez           123          20         Dean                t        Straight        229       LL Road Frame - Black, 62       733   337.2200
14230      Michael John  R                 Troyer           7909           9         Burt                r      Gringlesby        103             Thin-Jam Lock Nut 1       607   169.6000
14664      Morgan        M                 Hill               12          17       Albert                i          Ringer        433                LL Mountain Tire       937    24.9900
14809      Natalie       E                 Williams         7933          17       Albert                i          Ringer        479           Road-350-W Yellow, 42       983  1700.9900
14954      Nathaniel     C                 Howard          11648          21         Dirk                t        Stringer        276         Mountain-100 Silver, 38       780  3399.9900
15300      Olivia        D                 Bennett           102           2     Reginald                l  Blotchet-Halls        153                   Lock Washer 3       140     0.0000
15302      Olivia        E                 Howard           7899          13      Stearns                a      MacFeather        450                Front Derailleur       450    91.4900
15308      Olivia        K                 Cox             11624           5        Innes                e    del Castillo        373      Women's Mountain Shorts, M       373    69.9900
15543      Patrick       L                 Sanders         11665           1      Abraham                f          Bennet         47              Thin-Jam Hex Nut 4        47   441.6000
15651      Peter         E                 Black            7885           3       Cheryl                a          Carson        233         LL Road Frame - Red, 58       233   337.2200
15680      Philip        M                 Gutierrez       11659           7     Marjorie                r           Green        446                   Touring Pedal       950    80.9900
15941      Randall       A                 Ruiz              125          12     Charlene                o        Locksley        357               Women's Tights, S       357    74.9900
16034      Raymond       W                 Madan           13731          14      Heather                c        McBadden         39             Thin-Jam Hex Nut 10       543   144.0000
16266      Richard       J                 Martinez         7904           1      Abraham                f          Bennet         26                   Flat Washer 4       530     0.0000
16269      Richard       L                 Cooper          11614          10       Sheryl                u          Hunter        217                    AWC Logo Cap       217     8.9900
16281      Richard       M                 Brown           11654          22      Johnson                h           White        369                 Classic Vest, S       873    63.5000
16870      Ryan          C                 Davis           11671           2     Reginald                l  Blotchet-Halls        140                       Lock Ring       140   829.8000
16881      Ryan          J                 Alexander        7923          22      Johnson                h           White        323             LL Road Front Wheel       827    85.5650
17000      Samuel        B                 Johnston          134           9         Burt                r      Gringlesby        170                       HL Nipple       170   196.4000
17023      Samuel        L                 Robinson          206           4       Michel                e        DeFrance        259                Road-450 Red, 58       763  1457.9900
17541      Shaun         N                 Andersen            7           5        Innes                e    del Castillo        373      Women's Mountain Shorts, M       373    69.9900
17664      Shelley       N                 Dyck               44           1      Abraham                f          Bennet        463           Touring-3000 Blue, 54       967   742.3500
17968      Steven        L                 Peterson        13784          13      Stearns                a      MacFeather        383           Fender Set - Mountain       887    21.9800
18182      Tabitha       A                 Gonzalez           97           2     Reginald                l  Blotchet-Halls         73                      Hex Nut 15       577   472.8000
18197      Tabitha       M                 Rodriguez       11615           3       Cheryl                a          Carson        233         LL Road Frame - Red, 58       233   337.2200
18700      Timothy       L                 Sanders            16           3       Cheryl                a          Carson        187       LL Mountain Seat Assembly       187   133.3400
18723      Tina          J                 Lopez              37          21         Dirk                t        Stringer        276         Mountain-100 Silver, 38       780  3399.9900
18917      Trish         E                 Pederson         7918          14      Heather                c        McBadden        246  HL Mountain Frame - Silver, 48       750  1364.5000
19025      Tyrone        B                 Ruiz             7903           7     Marjorie                r           Green          9                 Chainring Bolts       513     0.0000
19410      Whitney       C                 Sanchez          7884          10       Sheryl                u          Hunter        217                    AWC Logo Cap       217     8.9900

In [585]:
tmpcstdf.reset_index(inplace=True)

In [579]:
tmpcstdf

     CustomerID CustFirstName CustMiddleInitial CustLastName  SalesID  EmployeeID EmpFirstName EmpMiddleInitial     EmpLastName  ProductID                     ProductName  Quantity      Price
0          2425          Brad                 M         Goel    11652          12     Charlene                o        Locksley        336   ML Mountain Frame - Black, 44       840   348.7600
1          2779       Bridget                 E       Chande    13758          19      Meander                m           Smith        433                LL Mountain Tire       433    24.9900
2          3000       Caitlin                 A       Howard       41           7     Marjorie                r           Green         30                   Flat Washer 7        30   418.8000
3          3241         Carla                 J     Gonzalez      166           1      Abraham                f          Bennet        230         LL Road Frame - Red, 44       230   337.2200
4          3541     Cassandra                 D        Madan      131           3       Cheryl                a          Carson        233         LL Road Frame - Red, 58       233   337.2200
5          3615     Catherine                 L       Murphy    11664           7     Marjorie                r           Green         30                   Flat Washer 7        30   418.8000
6          3664        Cedric                 W           Ma      101          22      Johnson                h           White        323             LL Road Front Wheel       827    85.5650
7          3752       Charles                 E      Sanders    13741          13      Stearns                a      MacFeather        429   LL Mountain Frame - Black, 42       933   249.7900
8          3782       Charles                 W       Watson     3064          19      Meander                m           Smith        433                LL Mountain Tire       433    24.9900
9          3987     Christian                 J       Garcia    11637           9         Burt                r      Gringlesby        103             Thin-Jam Lock Nut 1       607   169.6000
10         3989     Christian                 J       Hughes     7907           2     Reginald                l  Blotchet-Halls         73                      Hex Nut 15       577   472.8000
11         4097       Christy                 A     Andersen     7892          18         Anne                i          Ringer        340    ML Road Frame-W - Yellow, 44       340   594.8300
12         4182      Clarence                 L         Zeng        4           1      Abraham                f          Bennet        437                    ML Road Tire       437    24.9900
13         4341          Cole                 W         Cook    11613          16       Sylvia                a        Panteley        200                          Spokes       200   843.2000
14         4423       Colleen                 L         Nara     3077          16       Sylvia                a        Panteley        133                     Lock Nut 21       637    90.8000
15         4700        Dakota                 A      Russell      124           1      Abraham                f          Bennet         47              Thin-Jam Hex Nut 4        47   441.6000
16         4723          Dale                 C         Holt       94          19      Meander                m           Smith        136                     Lock Nut 15       640   548.4000
17         4941      Danielle                 J       Cooper     3116          17       Albert                i          Ringer        247  HL Mountain Frame - Silver, 46       247  1364.5000
18         4942      Danielle                 J      Sanders    11670           8  Morningstar                r          Greene        123                      Lock Nut 9       123   177.6000
19         4964         Danny                 J      Vazquez       34          12     Charlene                o        Locksley        336   ML Mountain Frame - Black, 44       840   348.7600
20         5314        Dennis                 G           Wu    11643          10       Sheryl                u          Hunter        196                 LL Spindle/Axle       700   418.4000
21         5676        Donald                 D     Martinez     7916           4       Michel                e        DeFrance        213         Sport-100 Helmet, Black       717    34.9900
22         6023       Eduardo                 G       Butler       43           9         Burt                r      Gringlesby        149                   Lock Washer 7       653   564.0000
23         6025       Eduardo                 J        Brown     7902          17       Albert                i          Ringer        500               ML Bottom Bracket       500   101.2400
24         6150         Edwin                 A         Deng    11619          21         Dirk                t        Stringer        297                Road-250 Red, 58       297  2443.3500
25         6541          Erik                 S    Gutierrez       96          10       Sheryl                u          Hunter        263                Road-450 Red, 52       263  1457.9900
26         6640         Ethan                 A        Clark     7921          15      Michael                '         O'Leary        293          Mountain-300 Black, 48       797  1079.9900
27         6641         Ethan                 A          Lal    13778          11        Livia                a          Karsen        289          Mountain-200 Black, 46       793  2294.9900
28         6664         Ethan                 M       Sharma      133           6          Ann                u            Dull        353       Headlights - Weatherproof       857    44.9900
29         6876      Fernando                 J      Jenkins    11630           7     Marjorie                r           Green        467         Touring-3000 Yellow, 50       467   742.3500
30         7482         Glenn                 A         Zeng     7873           1      Abraham                f          Bennet         47              Thin-Jam Hex Nut 4        47   441.6000
31         7602         Grant                 A     Andersen    13768          16       Sylvia                a        Panteley        133                     Lock Nut 21       637    90.8000
32         7700        Hailey                 J      Coleman      207           8  Morningstar                r          Greene         77                  Handlebar Tube        77   636.8000
33         7712        Hailey                 M        Lopez     7911          19      Meander                m           Smith        136                     Lock Nut 15       640   548.4000
34         7723        Hailey                 R       Rivera      126           3       Cheryl                a          Carson        166                   Metal Sheet 6       670   389.6000
35         7820        Hannah                 G      Jenkins     7896          12     Charlene                o        Locksley        403     LL Touring Frame - Blue, 62       403   333.4200
36         7849        Harold                 D       Subram    11660           1      Abraham                f          Bennet        463           Touring-3000 Blue, 54       967   742.3500
37         7956         Henry                 M       Prasad    13804           1      Abraham                f          Bennet        230         LL Road Frame - Red, 44       230   337.2200
38         8264      Isabella                 A        Evans       15          22      Johnson                h           White        369                 Classic Vest, S       873    63.5000
39         8327      Isabelle                 K    Henderson     7930          17       Albert                i          Ringer        433                LL Mountain Tire       937    24.9900
40         8435          Jack                 L        Hayes     7915          10       Sheryl                u          Hunter        196                 LL Spindle/Axle       700   418.4000
41         8450          Jack                 S      Richins    11655          16       Sylvia                a        Panteley        386  Short-Sleeve Classic Jersey, S       890    53.9900
42         8482       Jackson                 A       Foster      170          20         Dean                t        Straight        480           Road-350-W Yellow, 44       480  1700.9900
43         8804         James                 C        Evans    11693           1      Abraham                f          Bennet        483           Touring-3000 Blue, 44       483   742.3500
44         8929          Jane                 P        Greer    13735          17       Albert                i          Ringer        226         HL Road Frame - Red, 56       730  1431.5000
45         9000         Jared                 A         Gray       38          21         Dirk                t        Stringer         90          External Lock Washer 2        90     0.0000
46         9423         Jenny                 S        Liang        8          20         Dean                t        Straight        183                     LL Road Rim       687   306.0000
47         9530      Jermaine                 A       Kapoor    11640           9         Burt                r      Gringlesby        149                   Lock Washer 7       653   564.0000
48         9541      Jermaine                 J        Perez      163          17       Albert                i          Ringer        293          Mountain-300 Black, 48       293  1079.9900
49         9765         Jésus                 K        Munoz    11621           5        Innes                e    del Castillo        327    ML Road Frame-W - Yellow, 38       327   594.8300
50        10122        Johnny                 G        Kumar     7924          12     Charlene                o        Locksley        336   ML Mountain Frame - Black, 44       840   348.7600
51        10241      Jonathan                 J    Hernandez     7936           7     Marjorie                r           Green         30                   Flat Washer 7        30   418.8000
52        10366        Jordyn                 S      Coleman    11616          20         Dean                t        Straight        250   HL Mountain Frame - Black, 48       250  1349.6000
53        10471          José                 G        Lopez     7910           2     Reginald                l  Blotchet-Halls        119                     Lock Nut 16       623    88.0000
54        10491        Joseph                 J      Cantoni    13762          14      Heather                c        McBadden        497          Mountain-500 Black, 48       497   539.9900
55        10738         Julie                 M          Luo    11651          22      Johnson                h           White        323             LL Road Front Wheel       827    85.5650
56        11241     Katherine                 R         Cook       10          11        Livia                a          Karsen        310                      LL Headset       310    34.2000
57        11264      Kathleen                 A        Rubio       31           6          Ann                u            Dull        399                 Rear Derailleur       903   121.4600
58        11339       Katrina                 M       Sharma    11646          14      Heather                c        McBadden        246  HL Mountain Frame - Silver, 48       750  1364.5000
59        11464         Keith                 R          Pal    13791           8  Morningstar                r          Greene        493         Mountain-500 Silver, 52       997   564.9900
60        11818       Kristen                 R           Li    11636          15      Michael                '         O'Leary         86          External Lock Washer 7       590     0.0000
61        12065          Kyle                 T        Young    11657           1      Abraham                f          Bennet        416             LL Road Seat/Saddle       920    27.1200
62        12158         Larry                 S        Gomez     7919           4       Michel                e        DeFrance        259                Road-450 Red, 58       763  1457.9900
63        12300        Lauren                 W       Cooper        3           8  Morningstar                r          Greene        123                      Lock Nut 9       123   177.6000
64        12543          Lisa                 S         Chen     7900           7     Marjorie                r           Green        467         Touring-3000 Yellow, 50       467   742.3500
65        12892          Luke                 J      Simmons     7886          20         Dean                t        Straight        250   HL Mountain Frame - Black, 48       250  1349.6000
66        12941     Mackenzie                 A        Adams       93           5        Innes                e    del Castillo        327    ML Road Frame-W - Yellow, 38       327   594.8300
67        12964     Mackenzie                 M      Ramirez      130           1      Abraham                f          Bennet        416             LL Road Seat/Saddle       920    27.1200
68        13482         Mario                 H          Rai       33           1      Abraham                f          Bennet         26                   Flat Washer 4       530     0.0000
69        13615        Martin                 P        Patel     7890          11        Livia                a          Karsen        310                      LL Headset       310    34.2000
70        13627        Marvin                 C        Gomez    11642          20         Dean                t        Straight        183                     LL Road Rim       687   306.0000
71        13723         Mason                 M         Cook      174          17       Albert                i          Ringer        226         HL Road Frame - Red, 56       730  1431.5000
72        13845         Mayra                 S      Sanchez     7928           6          Ann                u            Dull        399                 Rear Derailleur       903   121.4600
73        13981       Melanie                 B      Russell    11618           4       Michel                e        DeFrance        280          Mountain-100 Black, 38       280  3374.9900
74        14000       Melanie                 N    Alexander      204           2     Reginald                l  Blotchet-Halls        140                       Lock Ring       140   829.8000
75        14023       Melinda                 T      Jimenez      123          20         Dean                t        Straight        229       LL Road Frame - Black, 62       733   337.2200
76        14230  Michael John                 R       Troyer     7909           9         Burt                r      Gringlesby        103             Thin-Jam Lock Nut 1       607   169.6000
77        14664        Morgan                 M         Hill       12          17       Albert                i          Ringer        433                LL Mountain Tire       937    24.9900
78        14809       Natalie                 E     Williams     7933          17       Albert                i          Ringer        479           Road-350-W Yellow, 42       983  1700.9900
79        14954     Nathaniel                 C       Howard    11648          21         Dirk                t        Stringer        276         Mountain-100 Silver, 38       780  3399.9900
80        15300        Olivia                 D      Bennett      102           2     Reginald                l  Blotchet-Halls        153                   Lock Washer 3       140     0.0000
81        15302        Olivia                 E       Howard     7899          13      Stearns                a      MacFeather        450                Front Derailleur       450    91.4900
82        15308        Olivia                 K          Cox    11624           5        Innes                e    del Castillo        373      Women's Mountain Shorts, M       373    69.9900
83        15543       Patrick                 L      Sanders    11665           1      Abraham                f          Bennet         47              Thin-Jam Hex Nut 4        47   441.6000
84        15651         Peter                 E        Black     7885           3       Cheryl                a          Carson        233         LL Road Frame - Red, 58       233   337.2200
85        15680        Philip                 M    Gutierrez    11659           7     Marjorie                r           Green        446                   Touring Pedal       950    80.9900
86        15941       Randall                 A         Ruiz      125          12     Charlene                o        Locksley        357               Women's Tights, S       357    74.9900
87        16034       Raymond                 W        Madan    13731          14      Heather                c        McBadden         39             Thin-Jam Hex Nut 10       543   144.0000
88        16266       Richard                 J     Martinez     7904           1      Abraham                f          Bennet         26                   Flat Washer 4       530     0.0000
89        16269       Richard                 L       Cooper    11614          10       Sheryl                u          Hunter        217                    AWC Logo Cap       217     8.9900
90        16281       Richard                 M        Brown    11654          22      Johnson                h           White        369                 Classic Vest, S       873    63.5000
91        16870          Ryan                 C        Davis    11671           2     Reginald                l  Blotchet-Halls        140                       Lock Ring       140   829.8000
92        16881          Ryan                 J    Alexander     7923          22      Johnson                h           White        323             LL Road Front Wheel       827    85.5650
93        17000        Samuel                 B     Johnston      134           9         Burt                r      Gringlesby        170                       HL Nipple       170   196.4000
94        17023        Samuel                 L     Robinson      206           4       Michel                e        DeFrance        259                Road-450 Red, 58       763  1457.9900
95        17541         Shaun                 N     Andersen        7           5        Innes                e    del Castillo        373      Women's Mountain Shorts, M       373    69.9900
96        17664       Shelley                 N         Dyck       44           1      Abraham                f          Bennet        463           Touring-3000 Blue, 54       967   742.3500
97        17968        Steven                 L     Peterson    13784          13      Stearns                a      MacFeather        383           Fender Set - Mountain       887    21.9800
98        18182       Tabitha                 A     Gonzalez       97           2     Reginald                l  Blotchet-Halls         73                      Hex Nut 15       577   472.8000
99        18197       Tabitha                 M    Rodriguez    11615           3       Cheryl                a          Carson        233         LL Road Frame - Red, 58       233   337.2200
100       18700       Timothy                 L      Sanders       16           3       Cheryl                a          Carson        187       LL Mountain Seat Assembly       187   133.3400
101       18723          Tina                 J        Lopez       37          21         Dirk                t        Stringer        276         Mountain-100 Silver, 38       780  3399.9900
102       18917         Trish                 E     Pederson     7918          14      Heather                c        McBadden        246  HL Mountain Frame - Silver, 48       750  1364.5000

In [586]:
cstdf = tmpcstdf[['CustomerID','CustFirstName','CustMiddleInitial','CustLastName']]

In [587]:
cstdf

     CustomerID CustFirstName CustMiddleInitial CustLastName
0          2425          Brad                 M         Goel
1          2779       Bridget                 E       Chande
2          3000       Caitlin                 A       Howard
3          3241         Carla                 J     Gonzalez
4          3541     Cassandra                 D        Madan
5          3615     Catherine                 L       Murphy
6          3664        Cedric                 W           Ma
7          3752       Charles                 E      Sanders
8          3782       Charles                 W       Watson
9          3987     Christian                 J       Garcia
10         3989     Christian                 J       Hughes
11         4097       Christy                 A     Andersen
12         4182      Clarence                 L         Zeng
13         4341          Cole                 W         Cook
14         4423       Colleen                 L         Nara
15         4700        Dakota                 A      Russell
16         4723          Dale                 C         Holt
17         4941      Danielle                 J       Cooper
18         4942      Danielle                 J      Sanders
19         4964         Danny                 J      Vazquez
20         5314        Dennis                 G           Wu
21         5676        Donald                 D     Martinez
22         6023       Eduardo                 G       Butler
23         6025       Eduardo                 J        Brown
24         6150         Edwin                 A         Deng
25         6541          Erik                 S    Gutierrez
26         6640         Ethan                 A        Clark
27         6641         Ethan                 A          Lal
28         6664         Ethan                 M       Sharma
29         6876      Fernando                 J      Jenkins
30         7482         Glenn                 A         Zeng
31         7602         Grant                 A     Andersen
32         7700        Hailey                 J      Coleman
33         7712        Hailey                 M        Lopez
34         7723        Hailey                 R       Rivera
35         7820        Hannah                 G      Jenkins
36         7849        Harold                 D       Subram
37         7956         Henry                 M       Prasad
38         8264      Isabella                 A        Evans
39         8327      Isabelle                 K    Henderson
40         8435          Jack                 L        Hayes
41         8450          Jack                 S      Richins
42         8482       Jackson                 A       Foster
43         8804         James                 C        Evans
44         8929          Jane                 P        Greer
45         9000         Jared                 A         Gray
46         9423         Jenny                 S        Liang
47         9530      Jermaine                 A       Kapoor
48         9541      Jermaine                 J        Perez
49         9765         Jésus                 K        Munoz
50        10122        Johnny                 G        Kumar
51        10241      Jonathan                 J    Hernandez
52        10366        Jordyn                 S      Coleman
53        10471          José                 G        Lopez
54        10491        Joseph                 J      Cantoni
55        10738         Julie                 M          Luo
56        11241     Katherine                 R         Cook
57        11264      Kathleen                 A        Rubio
58        11339       Katrina                 M       Sharma
59        11464         Keith                 R          Pal
60        11818       Kristen                 R           Li
61        12065          Kyle                 T        Young
62        12158         Larry                 S        Gomez
63        12300        Lauren                 W       Cooper
64        12543          Lisa                 S         Chen
65        12892          Luke                 J      Simmons
66        12941     Mackenzie                 A        Adams
67        12964     Mackenzie                 M      Ramirez
68        13482         Mario                 H          Rai
69        13615        Martin                 P        Patel
70        13627        Marvin                 C        Gomez
71        13723         Mason                 M         Cook
72        13845         Mayra                 S      Sanchez
73        13981       Melanie                 B      Russell
74        14000       Melanie                 N    Alexander
75        14023       Melinda                 T      Jimenez
76        14230  Michael John                 R       Troyer
77        14664        Morgan                 M         Hill
78        14809       Natalie                 E     Williams
79        14954     Nathaniel                 C       Howard
80        15300        Olivia                 D      Bennett
81        15302        Olivia                 E       Howard
82        15308        Olivia                 K          Cox
83        15543       Patrick                 L      Sanders
84        15651         Peter                 E        Black
85        15680        Philip                 M    Gutierrez
86        15941       Randall                 A         Ruiz
87        16034       Raymond                 W        Madan
88        16266       Richard                 J     Martinez
89        16269       Richard                 L       Cooper
90        16281       Richard                 M        Brown
91        16870          Ryan                 C        Davis
92        16881          Ryan                 J    Alexander
93        17000        Samuel                 B     Johnston
94        17023        Samuel                 L     Robinson
95        17541         Shaun                 N     Andersen
96        17664       Shelley                 N         Dyck
97        17968        Steven                 L     Peterson
98        18182       Tabitha                 A     Gonzalez
99        18197       Tabitha                 M    Rodriguez
100       18700       Timothy                 L      Sanders
101       18723          Tina                 J        Lopez
102       18917         Trish                 E     Pederson
103       19025        Tyrone                 B         Ruiz
104       19410       Whitney                 C      Sanchez
105       19482        Willie                 R          Gao
106       19640        Xavier                 M        Smith

creation of employee data frame

In [588]:
tmpempdf = df.groupby(['EmployeeID','EmpFirstName','EmpMiddleInitial','EmpLastName'])

In [589]:
tmpempdf = tmpempdf.first()

In [590]:
tmpempdf

                                                         SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  ProductID                     ProductName  Quantity      Price
EmployeeID EmpFirstName EmpMiddleInitial EmpLastName
1          Abraham      f                Bennet                4        4182      Clarence                 L         Zeng        437                    ML Road Tire       437    24.9900
2          Reginald     l                Blotchet-Halls       11        3023         Caleb              None           Li        119                     Lock Nut 16       623    88.0000
3          Cheryl       a                Carson               16       18700       Timothy                 L      Sanders        187       LL Mountain Seat Assembly       187   133.3400
4          Michel       e                DeFrance             40       12423          Levi              None       Prasad        213         Sport-100 Helmet, Black       717    34.9900
5          Innes        e                del Castillo          2        1964        Austin              None          Jai        306           Road-550-W Yellow, 48       810  1120.4900
6          Ann          u                Dull                 31       11264      Kathleen                 A        Rubio        399                 Rear Derailleur       903   121.4600
7          Marjorie     r                Green                36        7182     Gabrielle              None        Price        467         Touring-3000 Yellow, 50       467   742.3500
8          Morningstar  r                Greene                3       12300        Lauren                 W       Cooper        123                      Lock Nut 9       123   177.6000
9          Burt         r                Gringlesby           43        6023       Eduardo                 G       Butler        149                   Lock Washer 7       653   564.0000
10         Sheryl       u                Hunter               32        1941        Austin              None        Zhang        217                    AWC Logo Cap       217     8.9900
11         Livia        a                Karsen               10       11241     Katherine                 R         Cook        310                      LL Headset       310    34.2000
12         Charlene     o                Locksley             34        4964         Danny                 J      Vazquez        336   ML Mountain Frame - Black, 44       840   348.7600
13         Stearns      a                MacFeather           92        1300        Andrew              None         Hill         13                     Chain Stays        13    64.8000
14         Heather      c                McBadden              5       15723       Preston              None        Perez        246  HL Mountain Frame - Silver, 48       750  1364.5000
15         Michael      '                O'Leary              30       19482        Willie                 R          Gao         86          External Lock Washer 7       590     0.0000
16         Sylvia       a                Panteley             98        9964           Joe              None    Gutierrez        386  Short-Sleeve Classic Jersey, S       890    53.9900
17         Albert       i                Ringer                1       10482        Joseph              None        White        500               ML Bottom Bracket       500   101.2400
18         Anne         i                Ringer               42       14241       Micheal              None      Vazquez        340    ML Road Frame-W - Yellow, 44       340   594.8300
19         Meander      m                Smith                94        4723          Dale                 C         Holt        136                     Lock Nut 15       640   548.4000
20         Dean         t                Straight              8        9423         Jenny                 S        Liang        183                     LL Road Rim       687   306.0000
21         Dirk         t                Stringer             37       18723          Tina                 J        Lopez        276         Mountain-100 Silver, 38       780  3399.9900
22         Johnson      h                White                15        8264      Isabella                 A        Evans        369                 Classic Vest, S       873    63.5000

In [591]:
tmpempdf.reset_index(inplace=True)

In [592]:
tmpempdf

    EmployeeID EmpFirstName EmpMiddleInitial     EmpLastName  SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  ProductID                     ProductName  Quantity      Price
0            1      Abraham                f          Bennet        4        4182      Clarence                 L         Zeng        437                    ML Road Tire       437    24.9900
1            2     Reginald                l  Blotchet-Halls       11        3023         Caleb              None           Li        119                     Lock Nut 16       623    88.0000
2            3       Cheryl                a          Carson       16       18700       Timothy                 L      Sanders        187       LL Mountain Seat Assembly       187   133.3400
3            4       Michel                e        DeFrance       40       12423          Levi              None       Prasad        213         Sport-100 Helmet, Black       717    34.9900
4            5        Innes                e    del Castillo        2        1964        Austin              None          Jai        306           Road-550-W Yellow, 48       810  1120.4900
5            6          Ann                u            Dull       31       11264      Kathleen                 A        Rubio        399                 Rear Derailleur       903   121.4600
6            7     Marjorie                r           Green       36        7182     Gabrielle              None        Price        467         Touring-3000 Yellow, 50       467   742.3500
7            8  Morningstar                r          Greene        3       12300        Lauren                 W       Cooper        123                      Lock Nut 9       123   177.6000
8            9         Burt                r      Gringlesby       43        6023       Eduardo                 G       Butler        149                   Lock Washer 7       653   564.0000
9           10       Sheryl                u          Hunter       32        1941        Austin              None        Zhang        217                    AWC Logo Cap       217     8.9900
10          11        Livia                a          Karsen       10       11241     Katherine                 R         Cook        310                      LL Headset       310    34.2000
11          12     Charlene                o        Locksley       34        4964         Danny                 J      Vazquez        336   ML Mountain Frame - Black, 44       840   348.7600
12          13      Stearns                a      MacFeather       92        1300        Andrew              None         Hill         13                     Chain Stays        13    64.8000
13          14      Heather                c        McBadden        5       15723       Preston              None        Perez        246  HL Mountain Frame - Silver, 48       750  1364.5000
14          15      Michael                '         O'Leary       30       19482        Willie                 R          Gao         86          External Lock Washer 7       590     0.0000
15          16       Sylvia                a        Panteley       98        9964           Joe              None    Gutierrez        386  Short-Sleeve Classic Jersey, S       890    53.9900
16          17       Albert                i          Ringer        1       10482        Joseph              None        White        500               ML Bottom Bracket       500   101.2400
17          18         Anne                i          Ringer       42       14241       Micheal              None      Vazquez        340    ML Road Frame-W - Yellow, 44       340   594.8300
18          19      Meander                m           Smith       94        4723          Dale                 C         Holt        136                     Lock Nut 15       640   548.4000
19          20         Dean                t        Straight        8        9423         Jenny                 S        Liang        183                     LL Road Rim       687   306.0000
20          21         Dirk                t        Stringer       37       18723          Tina                 J        Lopez        276         Mountain-100 Silver, 38       780  3399.9900
21          22      Johnson                h           White       15        8264      Isabella                 A        Evans        369                 Classic Vest, S       873    63.5000

In [593]:
empdf = tmpempdf[['EmployeeID','EmpFirstName','EmpMiddleInitial','EmpLastName']]

In [594]:
empdf

    EmployeeID EmpFirstName EmpMiddleInitial     EmpLastName
0            1      Abraham                f          Bennet
1            2     Reginald                l  Blotchet-Halls
2            3       Cheryl                a          Carson
3            4       Michel                e        DeFrance
4            5        Innes                e    del Castillo
5            6          Ann                u            Dull
6            7     Marjorie                r           Green
7            8  Morningstar                r          Greene
8            9         Burt                r      Gringlesby
9           10       Sheryl                u          Hunter
10          11        Livia                a          Karsen
11          12     Charlene                o        Locksley
12          13      Stearns                a      MacFeather
13          14      Heather                c        McBadden
14          15      Michael                '         O'Leary
15          16       Sylvia                a        Panteley
16          17       Albert                i          Ringer
17          18         Anne                i          Ringer
18          19      Meander                m           Smith
19          20         Dean                t        Straight
20          21         Dirk                t        Stringer
21          22      Johnson                h           White

creation of Product data frame

In [595]:
tmpproddf = df.groupby(['ProductID','ProductName','Price'])

In [596]:
tmpproddf = tmpproddf.first()

In [597]:
tmpproddf

                                                    SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial     EmpLastName  Quantity
ProductID ProductName                    Price
1         Adjustable Race                1.6000           9           1         Aaron              None    Alexander           1      Abraham                f          Bennet        10
9         Chainring Bolts                0.0000         100       11782        Krista              None         Gill           7     Marjorie                r           Green       513
13        Chain Stays                    64.8000         92        1300        Andrew              None         Hill          13      Stearns                a      MacFeather        13
26        Flat Washer 4                  0.0000          33       13482         Mario                 H          Rai           1      Abraham                f          Bennet       530
30        Flat Washer 7                  418.8000        41        3000       Caitlin                 A       Howard           7     Marjorie                r           Green        30
39        Thin-Jam Hex Nut 10            144.0000       167       14782       Natalie              None         Reed          14      Heather                c        McBadden       543
43        Thin-Jam Hex Nut 16            72.8000        132       15182          Noah              None       Bryant          18         Anne                i          Ringer       547
47        Thin-Jam Hex Nut 4             441.6000       124        4700        Dakota                 A      Russell           1      Abraham                f          Bennet        47
56        Hex Nut 16                     75.4000         14       16482         Robin              None       Ortega           8  Morningstar                r          Greene       560
60        Hex Nut 9                      152.4000         6        6000       Eduardo              None       Walker          14      Heather                c        McBadden        60
73        Hex Nut 15                     472.8000        97       18182       Tabitha                 A     Gonzalez           2     Reginald                l  Blotchet-Halls       577
77        Handlebar Tube                 636.8000       207        7700        Hailey                 J      Coleman           8  Morningstar                r          Greene        77
86        External Lock Washer 7         0.0000          30       19482        Willie                 R          Gao          15      Michael                '         O'Leary       590
90        External Lock Washer 2         0.0000          38        9000         Jared                 A         Gray          21         Dirk                t        Stringer        90
103       Thin-Jam Lock Nut 1            169.6000       129        1423      Angelica              None    Alexander           9         Burt                r      Gringlesby       607
107       Thin-Jam Lock Nut 5            85.6000        121       10700        Julian              None      Jenkins          15      Michael                '         O'Leary       107
119       Lock Nut 16                    88.0000         11        3023         Caleb              None           Li           2     Reginald                l  Blotchet-Halls       623
123       Lock Nut 9                     177.6000         3       12300        Lauren                 W       Cooper           8  Morningstar                r          Greene       123
133       Lock Nut 21                    90.8000       3077        4423       Colleen                 L         Nara          16       Sylvia                a        Panteley       637
136       Lock Nut 15                    548.4000        94        4723          Dale                 C         Holt          19      Meander                m           Smith       640
137       Lock Nut 4                     183.2000      3109       13700         Mason              None       Wright          22      Johnson                h           White       137
140       Lock Ring                      829.8000       204       14000       Melanie                 N    Alexander           2     Reginald                l  Blotchet-Halls       140
149       Lock Washer 7                  564.0000        43        6023       Eduardo                 G       Butler           9         Burt                r      Gringlesby       653
153       Lock Washer 3                  0.0000         102       15300        Olivia                 D      Bennett           2     Reginald                l  Blotchet-Halls       140
166       Metal Sheet 6                  389.6000       126        7723        Hailey                 R       Rivera           3       Cheryl                a          Carson       670
170       HL Nipple                      196.4000       134       17000        Samuel                 B     Johnston           9         Burt                r      Gringlesby       170
179       Reflector                      910.8000      3080        9023        Jarrod              None         Rana          16       Sylvia                a        Panteley       683
183       LL Road Rim                    306.0000         8        9423         Jenny                 S        Liang          20         Dean                t        Straight       687
187       LL Mountain Seat Assembly      133.3400        16       18700       Timothy                 L      Sanders           3       Cheryl                a          Carson       187
196       LL Spindle/Axle                418.4000        91       10723         Julie              None          Jai          10       Sheryl                u          Hunter       700
200       Spokes                         843.2000        99         241       Adriana              None        Vance          16       Sylvia                a        Panteley       200
213       Sport-100 Helmet, Black        34.9900         40       12423          Levi              None       Prasad           4       Michel                e        DeFrance       717
217       AWC Logo Cap                   8.9900          32        1941        Austin              None        Zhang          10       Sheryl                u          Hunter       217
226       HL Road Frame - Red, 56        1431.5000      174       13723         Mason                 M         Cook          17       Albert                i          Ringer       730
229       LL Road Frame - Black, 62      337.2200       123       14023       Melinda                 T      Jimenez          20         Dean                t        Straight       733
230       LL Road Frame - Red, 44        337.2200       166        3241         Carla                 J     Gonzalez           1      Abraham                f          Bennet       230
233       LL Road Frame - Red, 58        337.2200       131        3541     Cassandra                 D        Madan           3       Cheryl                a          Carson       233
243       LL Road Frame - Black, 52      337.2200      3084       15423         Pablo              None  Rovira Diez          11        Livia                a          Karsen       747
246       HL Mountain Frame - Silver, 48 1364.5000        5       15723       Preston              None        Perez          14      Heather                c        McBadden       750
247       HL Mountain Frame - Silver, 46 1364.5000     3116        4941      Danielle                 J       Cooper          17       Albert                i          Ringer       247
250       HL Mountain Frame - Black, 48  1349.6000       13        5241           Deb              None       Waldal          20         Dean                t        Straight       250
259       Road-450 Red, 58               1457.9900      206       17023        Samuel                 L     Robinson           4       Michel                e        DeFrance       763
263       Road-450 Red, 52               1457.9900       96        6541          Erik                 S    Gutierrez          10       Sheryl                u          Hunter       263
276       Mountain-100 Silver, 38        3399.9900       37       18723          Tina                 J        Lopez          21         Dirk                t        Stringer       780
280       Mountain-100 Black, 38         3374.9900       45        8241      Isabella              None     Mitchell           4       Michel                e        DeFrance       280
289       Mountain-200 Black, 46         2294.9900      171         264      Adrienne              None      Jiménez          11        Livia                a          Karsen       793
293       Mountain-300 Black, 48         1079.9900      120         664    Alexandria              None     Peterson          15      Michael                '         O'Leary       797
297       Road-250 Red, 58               2443.3500      128        9941          Jodi              None         Deng          21         Dirk                t        Stringer       297
306       Road-550-W Yellow, 48          1120.4900        2        1964        Austin              None          Jai           5        Innes                e    del Castillo       810
310       LL Headset                     34.2000         10       11241     Katherine                 R         Cook          11        Livia                a          Karsen       310
323       LL Road Front Wheel            85.5650        101        3664        Cedric                 W           Ma          22      Johnson                h           White       827
327       ML Road Frame-W - Yellow, 38   594.8300        93       12941     Mackenzie                 A        Adams           5        Innes                e    del Castillo       327
336       ML Mountain Frame - Black, 44  348.7600        34        4964         Danny                 J      Vazquez          12     Charlene                o        Locksley       840
340       ML Road Frame-W - Yellow, 44   594.8300        42       14241       Micheal              None      Vazquez          18         Anne                i          Ringer       340
353       Headlights - Weatherproof      44.9900        133        6664         Ethan                 M       Sharma           6          Ann                u            Dull       857
357       Women's Tights, S              74.9900        125       15941       Randall                 A         Ruiz          12     Charlene                o        Locksley       357
369       Classic Vest, S                63.5000         15        8264      Isabella                 A        Evans          22      Johnson                h           White       873
373       Women's Mountain Shorts, M     69.9900          7       17541         Shaun                 N     Andersen           5        Innes                e    del Castillo       373
383       Fender Set - Mountain          21.9800        309        9664       Jessica              None    Rodriguez          13      Stearns                a      MacFeather       887
386       Short-Sleeve Classic Jersey, S 53.9900         98        9964           Joe              None    Gutierrez          16       Sylvia                a        Panteley       890
387       Short-Sleeve Classic Jersey, M 53.9900       3061       18941       Tristan              None       Butler          19      Meander                m           Smith       387
390       HL Touring Frame - Yellow, 60  1003.9100       90       19241      Virginia              None    Rodriguez          22      Johnson                h           White       390
399       Rear Derailleur                121.4600        31       11264      Kathleen                 A        Rubio           6          Ann                u            Dull       903
403       LL Touring Frame - Blue, 62    333.4200        39         782        Alicia              None      Chapman          12     Charlene                o        Locksley       403
416       LL Road Seat/Saddle            27.1200        130       12964     Mackenzie                 M      Ramirez           1      Abraham                f          Bennet       920
420       ML Touring Seat/Saddle         39.1400        122        2482       Brandon              None       Harris           6          Ann                u            Dull       420
429       LL Mountain Frame - Black, 42  249.7900      3096       14264       Michele              None         Raji          13      Stearns                a      MacFeather       933
433       LL Mountain Tire               24.9900         12       14664        Morgan                 M         Hill          17       Albert                i          Ringer       937
437       ML Road Tire                   24.9900          4        4182      Clarence                 L         Zeng           1      Abraham                f          Bennet       437
446       Touring Pedal                  80.9900         95       15964         Randy              None        Zhang           7     Marjorie                r           Green       950
450       Front Derailleur               91.4900        205        5482         Devin              None       Nelson          13      Stearns                a      MacFeather       450
463       Touring-3000 Blue, 54          742.3500        44       17664       Shelley                 N         Dyck           1      Abraham                f          Bennet       967
467       Touring-3000 Yellow, 50        742.3500        36        7182     Gabrielle              None        Price           7     Marjorie                r           Green       467
476       Touring-2000 Blue, 50          1214.8500      162       18964          Troy              None      Chandra          14      Heather                c        McBadden       980
479       Road-350-W Yellow, 42          1700.9900      127       19264        Walter              None      Jimenez          17       Albert                i          Ringer       983
480       Road-350-W Yellow, 44          1700.9900      170        8482       Jackson                 A       Foster          20         Dean                t        Straight       480
483       Touring-3000 Blue, 44          742.3500       135        8782         James              None        Kumar           1      Abraham                f          Bennet       483
493       Mountain-500 Silver, 52        564.9900      3100         905       Allison              None        Allen           8  Morningstar                r          Greene       997
497       Mountain-500 Black, 48         539.9900      3068       10182      Jonathan              None       Butler          14      Heather                c        McBadden       497
500       ML Bottom Bracket              101.2400         1       10482        Joseph              None        White          17       Albert                i          Ringer       500

In [598]:
tmpproddf.reset_index(inplace=True)

In [599]:
tmpproddf

    ProductID                     ProductName      Price  SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial     EmpLastName  Quantity
0           1                 Adjustable Race     1.6000        9           1         Aaron              None    Alexander           1      Abraham                f          Bennet        10
1           9                 Chainring Bolts     0.0000      100       11782        Krista              None         Gill           7     Marjorie                r           Green       513
2          13                     Chain Stays    64.8000       92        1300        Andrew              None         Hill          13      Stearns                a      MacFeather        13
3          26                   Flat Washer 4     0.0000       33       13482         Mario                 H          Rai           1      Abraham                f          Bennet       530
4          30                   Flat Washer 7   418.8000       41        3000       Caitlin                 A       Howard           7     Marjorie                r           Green        30
5          39             Thin-Jam Hex Nut 10   144.0000      167       14782       Natalie              None         Reed          14      Heather                c        McBadden       543
6          43             Thin-Jam Hex Nut 16    72.8000      132       15182          Noah              None       Bryant          18         Anne                i          Ringer       547
7          47              Thin-Jam Hex Nut 4   441.6000      124        4700        Dakota                 A      Russell           1      Abraham                f          Bennet        47
8          56                      Hex Nut 16    75.4000       14       16482         Robin              None       Ortega           8  Morningstar                r          Greene       560
9          60                       Hex Nut 9   152.4000        6        6000       Eduardo              None       Walker          14      Heather                c        McBadden        60
10         73                      Hex Nut 15   472.8000       97       18182       Tabitha                 A     Gonzalez           2     Reginald                l  Blotchet-Halls       577
11         77                  Handlebar Tube   636.8000      207        7700        Hailey                 J      Coleman           8  Morningstar                r          Greene        77
12         86          External Lock Washer 7     0.0000       30       19482        Willie                 R          Gao          15      Michael                '         O'Leary       590
13         90          External Lock Washer 2     0.0000       38        9000         Jared                 A         Gray          21         Dirk                t        Stringer        90
14        103             Thin-Jam Lock Nut 1   169.6000      129        1423      Angelica              None    Alexander           9         Burt                r      Gringlesby       607
15        107             Thin-Jam Lock Nut 5    85.6000      121       10700        Julian              None      Jenkins          15      Michael                '         O'Leary       107
16        119                     Lock Nut 16    88.0000       11        3023         Caleb              None           Li           2     Reginald                l  Blotchet-Halls       623
17        123                      Lock Nut 9   177.6000        3       12300        Lauren                 W       Cooper           8  Morningstar                r          Greene       123
18        133                     Lock Nut 21    90.8000     3077        4423       Colleen                 L         Nara          16       Sylvia                a        Panteley       637
19        136                     Lock Nut 15   548.4000       94        4723          Dale                 C         Holt          19      Meander                m           Smith       640
20        137                      Lock Nut 4   183.2000     3109       13700         Mason              None       Wright          22      Johnson                h           White       137
21        140                       Lock Ring   829.8000      204       14000       Melanie                 N    Alexander           2     Reginald                l  Blotchet-Halls       140
22        149                   Lock Washer 7   564.0000       43        6023       Eduardo                 G       Butler           9         Burt                r      Gringlesby       653
23        153                   Lock Washer 3     0.0000      102       15300        Olivia                 D      Bennett           2     Reginald                l  Blotchet-Halls       140
24        166                   Metal Sheet 6   389.6000      126        7723        Hailey                 R       Rivera           3       Cheryl                a          Carson       670
25        170                       HL Nipple   196.4000      134       17000        Samuel                 B     Johnston           9         Burt                r      Gringlesby       170
26        179                       Reflector   910.8000     3080        9023        Jarrod              None         Rana          16       Sylvia                a        Panteley       683
27        183                     LL Road Rim   306.0000        8        9423         Jenny                 S        Liang          20         Dean                t        Straight       687
28        187       LL Mountain Seat Assembly   133.3400       16       18700       Timothy                 L      Sanders           3       Cheryl                a          Carson       187
29        196                 LL Spindle/Axle   418.4000       91       10723         Julie              None          Jai          10       Sheryl                u          Hunter       700
30        200                          Spokes   843.2000       99         241       Adriana              None        Vance          16       Sylvia                a        Panteley       200
31        213         Sport-100 Helmet, Black    34.9900       40       12423          Levi              None       Prasad           4       Michel                e        DeFrance       717
32        217                    AWC Logo Cap     8.9900       32        1941        Austin              None        Zhang          10       Sheryl                u          Hunter       217
33        226         HL Road Frame - Red, 56  1431.5000      174       13723         Mason                 M         Cook          17       Albert                i          Ringer       730
34        229       LL Road Frame - Black, 62   337.2200      123       14023       Melinda                 T      Jimenez          20         Dean                t        Straight       733
35        230         LL Road Frame - Red, 44   337.2200      166        3241         Carla                 J     Gonzalez           1      Abraham                f          Bennet       230
36        233         LL Road Frame - Red, 58   337.2200      131        3541     Cassandra                 D        Madan           3       Cheryl                a          Carson       233
37        243       LL Road Frame - Black, 52   337.2200     3084       15423         Pablo              None  Rovira Diez          11        Livia                a          Karsen       747
38        246  HL Mountain Frame - Silver, 48  1364.5000        5       15723       Preston              None        Perez          14      Heather                c        McBadden       750
39        247  HL Mountain Frame - Silver, 46  1364.5000     3116        4941      Danielle                 J       Cooper          17       Albert                i          Ringer       247
40        250   HL Mountain Frame - Black, 48  1349.6000       13        5241           Deb              None       Waldal          20         Dean                t        Straight       250
41        259                Road-450 Red, 58  1457.9900      206       17023        Samuel                 L     Robinson           4       Michel                e        DeFrance       763
42        263                Road-450 Red, 52  1457.9900       96        6541          Erik                 S    Gutierrez          10       Sheryl                u          Hunter       263
43        276         Mountain-100 Silver, 38  3399.9900       37       18723          Tina                 J        Lopez          21         Dirk                t        Stringer       780
44        280          Mountain-100 Black, 38  3374.9900       45        8241      Isabella              None     Mitchell           4       Michel                e        DeFrance       280
45        289          Mountain-200 Black, 46  2294.9900      171         264      Adrienne              None      Jiménez          11        Livia                a          Karsen       793
46        293          Mountain-300 Black, 48  1079.9900      120         664    Alexandria              None     Peterson          15      Michael                '         O'Leary       797
47        297                Road-250 Red, 58  2443.3500      128        9941          Jodi              None         Deng          21         Dirk                t        Stringer       297
48        306           Road-550-W Yellow, 48  1120.4900        2        1964        Austin              None          Jai           5        Innes                e    del Castillo       810
49        310                      LL Headset    34.2000       10       11241     Katherine                 R         Cook          11        Livia                a          Karsen       310
50        323             LL Road Front Wheel    85.5650      101        3664        Cedric                 W           Ma          22      Johnson                h           White       827
51        327    ML Road Frame-W - Yellow, 38   594.8300       93       12941     Mackenzie                 A        Adams           5        Innes                e    del Castillo       327
52        336   ML Mountain Frame - Black, 44   348.7600       34        4964         Danny                 J      Vazquez          12     Charlene                o        Locksley       840
53        340    ML Road Frame-W - Yellow, 44   594.8300       42       14241       Micheal              None      Vazquez          18         Anne                i          Ringer       340
54        353       Headlights - Weatherproof    44.9900      133        6664         Ethan                 M       Sharma           6          Ann                u            Dull       857
55        357               Women's Tights, S    74.9900      125       15941       Randall                 A         Ruiz          12     Charlene                o        Locksley       357
56        369                 Classic Vest, S    63.5000       15        8264      Isabella                 A        Evans          22      Johnson                h           White       873
57        373      Women's Mountain Shorts, M    69.9900        7       17541         Shaun                 N     Andersen           5        Innes                e    del Castillo       373
58        383           Fender Set - Mountain    21.9800      309        9664       Jessica              None    Rodriguez          13      Stearns                a      MacFeather       887
59        386  Short-Sleeve Classic Jersey, S    53.9900       98        9964           Joe              None    Gutierrez          16       Sylvia                a        Panteley       890
60        387  Short-Sleeve Classic Jersey, M    53.9900     3061       18941       Tristan              None       Butler          19      Meander                m           Smith       387
61        390   HL Touring Frame - Yellow, 60  1003.9100       90       19241      Virginia              None    Rodriguez          22      Johnson                h           White       390
62        399                 Rear Derailleur   121.4600       31       11264      Kathleen                 A        Rubio           6          Ann                u            Dull       903
63        403     LL Touring Frame - Blue, 62   333.4200       39         782        Alicia              None      Chapman          12     Charlene                o        Locksley       403
64        416             LL Road Seat/Saddle    27.1200      130       12964     Mackenzie                 M      Ramirez           1      Abraham                f          Bennet       920
65        420          ML Touring Seat/Saddle    39.1400      122        2482       Brandon              None       Harris           6          Ann                u            Dull       420
66        429   LL Mountain Frame - Black, 42   249.7900     3096       14264       Michele              None         Raji          13      Stearns                a      MacFeather       933
67        433                LL Mountain Tire    24.9900       12       14664        Morgan                 M         Hill          17       Albert                i          Ringer       937
68        437                    ML Road Tire    24.9900        4        4182      Clarence                 L         Zeng           1      Abraham                f          Bennet       437
69        446                   Touring Pedal    80.9900       95       15964         Randy              None        Zhang           7     Marjorie                r           Green       950
70        450                Front Derailleur    91.4900      205        5482         Devin              None       Nelson          13      Stearns                a      MacFeather       450
71        463           Touring-3000 Blue, 54   742.3500       44       17664       Shelley                 N         Dyck           1      Abraham                f          Bennet       967
72        467         Touring-3000 Yellow, 50   742.3500       36        7182     Gabrielle              None        Price           7     Marjorie                r           Green       467
73        476           Touring-2000 Blue, 50  1214.8500      162       18964          Troy              None      Chandra          14      Heather                c        McBadden       980
74        479           Road-350-W Yellow, 42  1700.9900      127       19264        Walter              None      Jimenez          17       Albert                i          Ringer       983
75        480           Road-350-W Yellow, 44  1700.9900      170        8482       Jackson                 A       Foster          20         Dean                t        Straight       480
76        483           Touring-3000 Blue, 44   742.3500      135        8782         James              None        Kumar           1      Abraham                f          Bennet       483
77        493         Mountain-500 Silver, 52   564.9900     3100         905       Allison              None        Allen           8  Morningstar                r          Greene       997
78        497          Mountain-500 Black, 48   539.9900     3068       10182      Jonathan              None       Butler          14      Heather                c        McBadden       497
79        500               ML Bottom Bracket   101.2400        1       10482        Joseph              None        White          17       Albert                i          Ringer       500

In [600]:
proddf = tmpproddf[['ProductID','ProductName','Price']]

In [601]:
proddf

    ProductID                     ProductName      Price
0           1                 Adjustable Race     1.6000
1           9                 Chainring Bolts     0.0000
2          13                     Chain Stays    64.8000
3          26                   Flat Washer 4     0.0000
4          30                   Flat Washer 7   418.8000
5          39             Thin-Jam Hex Nut 10   144.0000
6          43             Thin-Jam Hex Nut 16    72.8000
7          47              Thin-Jam Hex Nut 4   441.6000
8          56                      Hex Nut 16    75.4000
9          60                       Hex Nut 9   152.4000
10         73                      Hex Nut 15   472.8000
11         77                  Handlebar Tube   636.8000
12         86          External Lock Washer 7     0.0000
13         90          External Lock Washer 2     0.0000
14        103             Thin-Jam Lock Nut 1   169.6000
15        107             Thin-Jam Lock Nut 5    85.6000
16        119                     Lock Nut 16    88.0000
17        123                      Lock Nut 9   177.6000
18        133                     Lock Nut 21    90.8000
19        136                     Lock Nut 15   548.4000
20        137                      Lock Nut 4   183.2000
21        140                       Lock Ring   829.8000
22        149                   Lock Washer 7   564.0000
23        153                   Lock Washer 3     0.0000
24        166                   Metal Sheet 6   389.6000
25        170                       HL Nipple   196.4000
26        179                       Reflector   910.8000
27        183                     LL Road Rim   306.0000
28        187       LL Mountain Seat Assembly   133.3400
29        196                 LL Spindle/Axle   418.4000
30        200                          Spokes   843.2000
31        213         Sport-100 Helmet, Black    34.9900
32        217                    AWC Logo Cap     8.9900
33        226         HL Road Frame - Red, 56  1431.5000
34        229       LL Road Frame - Black, 62   337.2200
35        230         LL Road Frame - Red, 44   337.2200
36        233         LL Road Frame - Red, 58   337.2200
37        243       LL Road Frame - Black, 52   337.2200
38        246  HL Mountain Frame - Silver, 48  1364.5000
39        247  HL Mountain Frame - Silver, 46  1364.5000
40        250   HL Mountain Frame - Black, 48  1349.6000
41        259                Road-450 Red, 58  1457.9900
42        263                Road-450 Red, 52  1457.9900
43        276         Mountain-100 Silver, 38  3399.9900
44        280          Mountain-100 Black, 38  3374.9900
45        289          Mountain-200 Black, 46  2294.9900
46        293          Mountain-300 Black, 48  1079.9900
47        297                Road-250 Red, 58  2443.3500
48        306           Road-550-W Yellow, 48  1120.4900
49        310                      LL Headset    34.2000
50        323             LL Road Front Wheel    85.5650
51        327    ML Road Frame-W - Yellow, 38   594.8300
52        336   ML Mountain Frame - Black, 44   348.7600
53        340    ML Road Frame-W - Yellow, 44   594.8300
54        353       Headlights - Weatherproof    44.9900
55        357               Women's Tights, S    74.9900
56        369                 Classic Vest, S    63.5000
57        373      Women's Mountain Shorts, M    69.9900
58        383           Fender Set - Mountain    21.9800
59        386  Short-Sleeve Classic Jersey, S    53.9900
60        387  Short-Sleeve Classic Jersey, M    53.9900
61        390   HL Touring Frame - Yellow, 60  1003.9100
62        399                 Rear Derailleur   121.4600
63        403     LL Touring Frame - Blue, 62   333.4200
64        416             LL Road Seat/Saddle    27.1200
65        420          ML Touring Seat/Saddle    39.1400
66        429   LL Mountain Frame - Black, 42   249.7900
67        433                LL Mountain Tire    24.9900
68        437                    ML Road Tire    24.9900
69        446                   Touring Pedal    80.9900
70        450                Front Derailleur    91.4900
71        463           Touring-3000 Blue, 54   742.3500
72        467         Touring-3000 Yellow, 50   742.3500
73        476           Touring-2000 Blue, 50  1214.8500
74        479           Road-350-W Yellow, 42  1700.9900
75        480           Road-350-W Yellow, 44  1700.9900
76        483           Touring-3000 Blue, 44   742.3500
77        493         Mountain-500 Silver, 52   564.9900
78        497          Mountain-500 Black, 48   539.9900
79        500               ML Bottom Bracket   101.2400

In [602]:
#review the data once after performing the transformations
df.head(10)

   SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial EmpLastName  ProductID            ProductName  Quantity     Price
0        4        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437           ML Road Tire       437   24.9900
1        9           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1        Adjustable Race        10    1.6000
2       20        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437           ML Road Tire       437   24.9900
3       25           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1        Adjustable Race        26    1.6000
4       33       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26          Flat Washer 4       530    0.0000
5       44       17664       Shelley                 N         Dyck           1      Abraham                f      Bennet        463  Touring-3000 Blue, 54       967  742.3500
6       49       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26          Flat Washer 4       530    0.0000
7       60       17664       Shelley                 N         Dyck           1      Abraham                f      Bennet        463  Touring-3000 Blue, 54       967  742.3500
8       65       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26          Flat Washer 4       530    0.0000
9       76       17664       Shelley                 N         Dyck           1      Abraham                f      Bennet        463  Touring-3000 Blue, 54       967  742.3500

Create a new column by multiplying the Price and the Quantity

In [603]:
df.dtypes

SalesID               int64
CustomerID            int64
CustFirstName        object
CustMiddleInitial    object
CustLastName         object
EmployeeID            int64
EmpFirstName         object
EmpMiddleInitial     object
EmpLastName          object
ProductID             int64
ProductName          object
Quantity              int64
Price                object
dtype: object

In [604]:
# multiply the Quantity and the Price to get totalprice
df['Quantity'] = pd.to_numeric(df['Quantity'], downcast="float")
df['Price'] = pd.to_numeric(df['Price'], downcast="float")

In [605]:
df.dtypes

SalesID                int64
CustomerID             int64
CustFirstName         object
CustMiddleInitial     object
CustLastName          object
EmployeeID             int64
EmpFirstName          object
EmpMiddleInitial      object
EmpLastName           object
ProductID              int64
ProductName           object
Quantity             float32
Price                float32
dtype: object

In [606]:
df['TotalPrice'] = df['Quantity'] * df['Price']

In [607]:
df.head(5)

   SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial EmpLastName  ProductID      ProductName  Quantity  Price  TotalPrice
0        4        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire    437.00  24.99   10,920.63
1        9           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1  Adjustable Race     10.00   1.60       16.00
2       20        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437     ML Road Tire    437.00  24.99   10,920.63
3       25           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1  Adjustable Race     26.00   1.60       41.60
4       33       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26    Flat Washer 4    530.00   0.00        0.00

In [608]:
df['TotalPrice'].round(decimals=2)

0         10,920.63
1             16.00
2         10,920.63
3             41.60
4              0.00
            ...
129464    55,435.50
129465   391,524.88
129466    70,762.26
129467    55,435.50
129468   391,524.88
Name: TotalPrice, Length: 129469, dtype: float32

In [609]:
df

        SalesID  CustomerID CustFirstName CustMiddleInitial CustLastName  EmployeeID EmpFirstName EmpMiddleInitial EmpLastName  ProductID                    ProductName  Quantity    Price  TotalPrice
0             4        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437                   ML Road Tire    437.00    24.99   10,920.63
1             9           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1                Adjustable Race     10.00     1.60       16.00
2            20        4182      Clarence                 L         Zeng           1      Abraham                f      Bennet        437                   ML Road Tire    437.00    24.99   10,920.63
3            25           1         Aaron              None    Alexander           1      Abraham                f      Bennet          1                Adjustable Race     26.00     1.60       41.60
4            33       13482         Mario                 H          Rai           1      Abraham                f      Bennet         26                  Flat Washer 4    530.00     0.00        0.00
...         ...         ...           ...               ...          ...         ...          ...              ...         ...        ...                            ...       ...      ...         ...
129464   129366       16281       Richard                 M        Brown          22      Johnson                h       White        369                Classic Vest, S    873.00    63.50   55,435.50
129465   129399        7477         Glenn              None           Lu          22      Johnson                h       White        390  HL Touring Frame - Yellow, 60    390.00 1,003.91  391,524.88
129466   129427       10738         Julie                 M          Luo          22      Johnson                h       White        323            LL Road Front Wheel    827.00    85.57   70,762.26
129467   129430       16281       Richard                 M        Brown          22      Johnson                h       White        369                Classic Vest, S    873.00    63.50   55,435.50
129468   129463        7477         Glenn              None           Lu          22      Johnson                h       White        390  HL Touring Frame - Yellow, 60    390.00 1,003.91  391,524.88

[129469 rows x 14 columns]

create the Fact table data frame

In [610]:
dfsales = df[['SalesID','EmployeeID','CustomerID','ProductID','Quantity','TotalPrice']]

In [611]:
dfsales.head(10)

   SalesID  EmployeeID  CustomerID  ProductID  Quantity  TotalPrice
0        4           1        4182        437    437.00   10,920.63
1        9           1           1          1     10.00       16.00
2       20           1        4182        437    437.00   10,920.63
3       25           1           1          1     26.00       41.60
4       33           1       13482         26    530.00        0.00
5       44           1       17664        463    967.00  717,852.44
6       49           1       13482         26    530.00        0.00
7       60           1       17664        463    967.00  717,852.44
8       65           1       13482         26    530.00        0.00
9       76           1       17664        463    967.00  717,852.44

# Creation of Star Schema

In [ ]:
# Import the package pymysql for making a connection to the database
import pymysql

In [ ]:
# Connect to the database
connection = pymysql.connect(host='localhost',
                         user='root',
                         password='Csoares#12',
                         db='dm_etl')

In [ ]:
connection

In [ ]:
# create cursor
cursor=connection.cursor()

In [ ]:
cursor.execute("USE dm_etl")
connection.commit()

In [ ]:
# create the Customer Table
cursor.execute("""CREATE TABLE CustDetails
    (CustomerID INT NOT NULL,
     CustFirstName varchar(255) NULL,
     CustMiddleInitial varchar(255) NULL,
     CustLastName varchar(255) NULL,
     PRIMARY KEY (CustomerID)
     )
     """)

connection.commit()

In [ ]:
# create the Employee Table
cursor.execute("""CREATE TABLE EmpDetails
    (EmployeeID INT NOT NULL,
     EmpFirstName varchar(255) NULL,
     EmpMiddleInitial varchar(255) NULL,
     EmpLastName varchar(255) NULL,
     PRIMARY KEY (EmployeeID)
     )
     """)

connection.commit()

In [ ]:
# create the Product Table
cursor.execute("""CREATE TABLE ProductDetails
    (ProductID INT NOT NULL,
     ProductName varchar(255) NULL,
     Price float NULL,
     PRIMARY KEY (ProductID)
     )
     """)

connection.commit()

In [ ]:
# create the sales table
cursor.execute("""CREATE TABLE SalesDetails
    (SalesID int NOT NULL,
     CustomerID int NULL,
     EmployeeID int NULL,
     ProductID int NULL,
     Quantity int NULL,
     TotalPrice float NULL,
     FOREIGN KEY (CustomerID) REFERENCES  CustDetails(CustomerID),
     FOREIGN KEY (EmployeeID) REFERENCES EmpDetails(EmployeeID),
     FOREIGN KEY (ProductID) REFERENCES ProductDetails(ProductID)
     )
     """)

connection.commit()

In [ ]:
# creating column list for insertion
cols = "`,`".join([str(i) for i in cstdf.columns.tolist()])

# Insert DataFrame recrds one by one.
for i,row in cstdf.iterrows():
    sql = "INSERT INTO `custdetails` (`" +cols + "`) VALUES (" + "%s,"*(len(row)-1) + "%s)"
    cursor.execute(sql, tuple(row))

    # the connection is not autocommitted by default, so we must commit to save our changes
    connection.commit()

In [ ]:
# creating column list for insertion
cols = "`,`".join([str(i) for i in empdf.columns.tolist()])

# Insert DataFrame recrds one by one.
for i,row in empdf.iterrows():
    sql = "INSERT INTO `empdetails` (`" +cols + "`) VALUES (" + "%s,"*(len(row)-1) + "%s)"
    cursor.execute(sql, tuple(row))

    # the connection is not autocommitted by default, so we must commit to save our changes
    connection.commit()

In [ ]:
# creating column list for insertion
cols = "`,`".join([str(i) for i in proddf.columns.tolist()])

# Insert DataFrame recrds one by one.
for i,row in proddf.iterrows():
    sql = "INSERT INTO `productdetails` (`" +cols + "`) VALUES (" + "%s,"*(len(row)-1) + "%s)"
    cursor.execute(sql, tuple(row))

    # the connection is not autocommitted by default, so we must commit to save our changes
    connection.commit()

In [ ]:
# creating column list for insertion
cols = "`,`".join([str(i) for i in dfsales.columns.tolist()])

# Insert DataFrame recrds one by one.
for i,row in dfsales.iterrows():
    sql = "INSERT INTO `salesdetails` (`" +cols + "`) VALUES (" + "%s,"*(len(row)-1) + "%s)"
    cursor.execute(sql, tuple(row))

    # the connection is not autocommitted by default, so we must commit to save our changes
    connection.commit()